<table class="table table-striped table-condensed">
<thead>
  <tr>
    <th>Wiki</th>
    <th>Description</th>
    <th>Mail</th>
    <th>Date</th>
  </tr>
</thead>
<tbody>
  <?php foreach($listWikis as $wiki) : ?>
  <tr>
    <td><a href="<?php echo $wiki['url'];?>"><?php echo $wiki['name'];?></a></td>
    <td><?php echo $wiki['description'];?></td>
    <td><?php echo $wiki['mail'];?></td>
    <td><?php echo $wiki['date'];?></td>
  </tr>
  <?php endforeach; ?>
</tbody>
</table>