<div id="alertesList">
    <?php $this->printAlertesList(); ?>
</div>
<?php //Attention il ne faut pas changer class et id du formulaire sinon hashcash ne fonctionne plus.?>	

<form id="newWiki" class="form-horizontal" method="post">
	<div class="control-group">
        <label class="control-label">Nom du wiki</label>
        <div class="controls">
        	<input type="text" name="wikiName" class="input-xlarge" placeholder="Nom du wiki (10 caract&egrave;res max)" required="required" maxlength="10" <?php 
         		if (isset($_POST['wikiName'])) 
					echo 'value = "'.$_POST['wikiName'].'"'; 
				?> /> 
          	<p class="help-block">10 caract&egrave;res maximum, uniquement des alpha num&eacute;riques.</p>
        </div>
    </div>
	<div class="control-group">
        <label class="control-label">Mail</label>
        <div class="controls">
        	<input 	type="email" name="mail" class="input-xlarge"
						placeholder="Votre adresse mail" 
						required="required"
						<?php 
							if (isset($_POST['mail']))
								echo 'value = "'.$_POST['mail'].'"'; 
						?> />
          	<p class="help-block">Elle sera notre contact pour la maintenance de votre wiki.</p>
        </div>
    </div>	
    <div class="control-group">
        <label class="control-label">Description</label>
        <div class="controls">
        	<textarea name="description" class="input-xlarge"
						placeholder="Une courte description de votre projet (140 caract&egrave;res max)." 
						  maxlength="140" ><?php 
						 	if (isset($_POST['description'])) 
						  		echo $_POST['description']; 
							?></textarea> 
          	<p class="help-block">D&eacute;crivez rapidement le projet auquel est rattach&eacute; ce wiki. (140 caract&egrave;res maximum).</p>
        </div>
    </div>
     <div class="control-group">
        <label class="control-label">Th&egrave;me graphique</label>
        <div class="controls">
        	<select id="theme" name="theme" onChange="changeThumb()" class="input-xlarge">
        		<?php $this->printThemesList();?>
			</select> 
          	<p class="help-block">Choisissez le th&egrave;me graphique par d&eacute;faut de votre nouveau Wiki.</p>
        </div>
    </div>
    <div class="form-actions">
    	<?php echo $this->HashCash() ?>
    	<script type="text/javascript">
			document.write('<button class="btn btn-large btn-primary" type="submit" name="action" value="create" id="submit">Cr&eacute;er un nouveau wiki</button>');
		</script>
    	<noscript>Formulaire prot&eacute;g&eacute; via JavaScript, <br />Merci de l'activer.</noscript> 
    </div>
</form>
<div id="wikisList">
	<?php $this->printWikisList(); ?>
</div>

<script type="text/JavaScript">
	function changeThumb(){
		var thumb = document
						.getElementById('theme')
						.options[document
									.getElementById('theme')
									.selectedIndex]
						.getAttribute('thumb');
		document.getElementById('thumb').src = thumb;
	}

	function hide(moi){
		moi.style.display = 'none';
	}

</script>