version: '2'

services:
    yeswiki:
        image: lavoweb/php-5.6
        container_name: yeswiki
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
        links:
            - db:db

    db:
        image: mysql:5.5
        container_name: db
        volumes:
            - ./.db:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root

    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: myadmin
        ports:
            - "8080:80"
        links:
            - db:db