version: '3.3'

services:
    yeswiki:
        build: .
        container_name: yeswiki
        ports:
            - "81:80"
        # these volumes help develop locally, close to what is shipped on Docker Hub
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        environment:
            YESWIKI_MYSQL_HOST: db
            YESWIKI_MYSQL_USER: root
            YESWIKI_MYSQL_PASSWORD: root
            YESWIKI_MYSQL_DATABASE: yeswiki_dev

    db:
        image: mysql:5.6
        container_name: db
        volumes:
            - ./.db:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=yeswiki_dev
            - MYSQL_ROOT_PASSWORD=root
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
            timeout: 20s
            retries: 10

    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: myadmin
        ports:
            - "8080:80"
        depends_on:
            - db
        environment:
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: root
