version: '3.3'

services:
    yeswiki:
        build: .
        container_name: yeswiki
        ports:
            - "81:80"
        # these volumes help develop locally, close to what is shipped on Docker Hub
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        environment:
            VIRTUAL_HOST: yeswiki.docker
            VIRTUAL_PORT: 80
        # Install php et js vendors
        # Launch apache as lavoweb/php-7.3:composer
        command: bash -c "make install && apache2-foreground"

    db:
        image: mysql:5.6
        container_name: db
        volumes:
            - ./.db:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=yeswiki_dev
            - MYSQL_ROOT_PASSWORD=root
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
            timeout: 20s
            retries: 10

    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: myadmin
        ports:
            - "8080:80"
        depends_on:
            - db
        environment:
            VIRTUAL_HOST: myadmin.docker
            VIRTUAL_PORT: 80
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: root

    # add to wakka.config.php
    #  'contact_mail_func' => 'smtp',
    #  'contact_smtp_host' => 'mail',
    # then browse email interception on http://localhost:8025
    mail:
        image: diyan/mailhog
        container_name: mail
        ports:
            - "1025:1025"
            - "8025:8025"
        environment:
            VIRTUAL_HOST: mail.docker
            VIRTUAL_PORT: 8025
