import { defineConfig, globalIgnores } from 'eslint/config'
import globals from 'globals'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import js from '@eslint/js'
import { FlatCompat } from '@eslint/eslintrc'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const compat = new FlatCompat({
  baseDirectory: __dirname,
  recommendedConfig: js.configs.recommended,
  allConfig: js.configs.all
})

// Lint the code this repo writes, and nothing else. Third-party JS is not ours to restyle,
// and one vendored file drowning the report is how a linter stops being read at all.
export default defineConfig([globalIgnores([
  // third-party code, wherever it sits
  '**/vendor/',
  // Ace resolves its dynamically-loaded modules against basePath, which ace-wrapper.js sets
  // to `javascripts` -- so this vendored Ace extension cannot live under vendor/ with the
  // rest of Ace without breaking the editor's search box. It was ignored as
  // `tools/aceditor/presentation/javascripts/ext-searchbox.js` until aceditor became core;
  // the file moved and the rule did not, which is why it accounted for 1306 of the 2249
  // problems `eslint .` reported. (javascripts/mode-yeswiki.js sits beside it for the same
  // basePath reason but is ours, and is linted.)
  'javascripts/ext-searchbox.js',
  // generated by src/build-icon-sprite.mjs
  'javascripts/yw-icon-map.js',
  // per-instance content, not part of the repo
  '**/custom/',
]), {
  extends: compat.extends('airbnb-base'),

  languageOptions: {
    globals: {
      ...globals.browser,
      wiki: 'writable',
      // ticket 14: the one initialisation convention, defined in javascripts/yw-init.js
      // (loaded first and non-deferred, so it exists before any deferred, module or
      // fragment-loaded caller runs)
      ywInit: 'readable',
      ywInitEach: 'readable',
      ywAssets: 'readable',
      // vendored htmx (javascripts/vendor/htmx), loaded on every page by {{linkjavascript}}
      htmx: 'readable',
      Vue: 'readable',
      Sortable: 'readable',
      // Leaflet global (javascripts/vendor/leaflet)
      L: 'readable',
      Vditor: 'readable',
      _t: 'readable',
      ace: 'writable',
      toastMessage: 'readable',
      multiDeleteService: 'readable',
      usersTableService: 'readable',
      // page-level config globals injected by forms_form.twig (form designer)
      groupsList: 'readable',
      formAndListIds: 'readable',
      // page-level config globals injected by theme-selector-with-form.twig
      themeSelectorTranslation: 'readable',
      customCSSPresetsPrefix: 'readable',
      geolocationHelper: 'readable',
      // page-level config globals injected by reactions templates
      blockReactionRemove: 'readable',
      blockReactionRemoveMessage: 'readable',
      Html5Qrcode: 'readable',
      Html5QrcodeSupportedFormats: 'readable',
      // p5.js "global mode" API, used by javascripts/qrcodetroc-visualisation.js
      p5: 'readable',
      resizeCanvas: 'readable',
      createCanvas: 'readable',
      random: 'readable',
      color: 'readable',
      width: 'readable',
      height: 'readable',
      sin: 'readable',
      cos: 'readable',
      noStroke: 'readable',
      noFill: 'readable',
      fill: 'readable',
      stroke: 'readable',
      ellipse: 'readable',
      rect: 'readable',
      line: 'readable',
      dist: 'readable',
      mouseX: 'readable',
      mouseY: 'readable',
      textAlign: 'readable',
      text: 'readable',
      background: 'readable',
      CENTER: 'readable',
      LEFT: 'readable'
    },

    ecmaVersion: 13,
    sourceType: 'module'
  },

  rules: {
    semi: ['error', 'never'],

    // long embedded data (SVG icon paths, HTML template literals, URLs) is exempt
    'max-len': ['error', { code: 104, ignoreStrings: true, ignoreTemplateLiterals: true, ignoreUrls: true }],

    'vars-on-top': 'off',
    'class-methods-use-this': 'off',
    'import/no-unresolved': 'off',
    'import/extensions': ['error', 'always'],
    'import/prefer-default-export': ['off'],
    'no-use-before-define': ['off'],
    eqeqeq: ['error', 'smart'],
    'comma-dangle': ['error', 'never'],

    'object-curly-newline': ['error', { multiline: true }],

    'func-names': ['error', 'never'],
    'space-before-function-paren': ['error', 'never'],

    'lines-between-class-members': ['error', 'always', { exceptAfterSingleLine: true }],

    'no-new': 'off',
    'no-restricted-syntax': 'off',
    'guard-for-in': 'off'
  }
}])
