import { defineConfig, globalIgnores } from 'eslint/config'
import globals from 'globals'
import js from '@eslint/js'
import prettier from 'eslint-config-prettier'

// Formatting is Prettier's, correctness is ESLint's, and the two no longer overlap.
//
// This extended `airbnb-base` until 2026-08. That config's last release is 15.0.0 (2021),
// it is eslintrc-only -- hence the `FlatCompat` bridge that used to be here -- and most of
// what it contributed was *stylistic*: `comma-dangle`, `operator-linebreak`,
// `implicit-arrow-linebreak`, `max-len`. Every one of those contradicts Prettier, which
// already formats this repo's CSS, so writing a new file meant satisfying two formatters
// with different opinions and running `prettier --write` on an old one produced 34 lint
// errors. One of them had to go.
//
// So: `js.configs.recommended` for the bugs, a short list of extra rules below for the
// mistakes this codebase actually makes, and `eslint-config-prettier` LAST to switch off
// anything stylistic that ever creeps back in. It disables nothing today -- `recommended`
// carries no formatting rules -- and that is the point: it is the guard that keeps it so.

// Lint the code this repo writes, and nothing else. Third-party JS is not ours to restyle,
// and one vendored file drowning the report is how a linter stops being read at all.
export default defineConfig([
  globalIgnores([
    // third-party code, wherever it sits
    '**/vendor/',
    // Ace resolves its dynamically-loaded modules against basePath, which ace-wrapper.js sets
    // to `javascripts` -- so this vendored Ace extension cannot live under vendor/ with the
    // rest of Ace without breaking the editor's search box. It was ignored as
    // `tools/aceditor/presentation/javascripts/ext-searchbox.js` until aceditor became core;
    // the file moved and the rule did not, which is why it accounted for 1306 of the 2249
    // problems `eslint .` reported. (javascripts/mode-yeswiki.js sits beside it for the same
    // basePath reason but is ours, and is linted.)
    'javascripts/ext-searchbox.js',
    // generated by src/build-icon-sprite.mjs
    'javascripts/yw-icon-map.js',
    // per-instance content, not part of the repo
    '**/custom/',
  ]),
  {
    extends: [js.configs.recommended, prettier],

    languageOptions: {
      globals: {
        ...globals.browser,
        wiki: 'writable',
        // ticket 14: the one initialisation convention, defined in javascripts/yw-init.js
        // (loaded first and non-deferred, so it exists before any deferred, module or
        // fragment-loaded caller runs)
        ywInit: 'readable',
        ywInitEach: 'readable',
        ywAssets: 'readable',
        // vendored htmx (javascripts/vendor/htmx), loaded on every page by {{linkjavascript}}
        htmx: 'readable',
        Vue: 'readable',
        Sortable: 'readable',
        // Leaflet global (javascripts/vendor/leaflet)
        L: 'readable',
        Vditor: 'readable',
        _t: 'readable',
        ace: 'writable',
        toastMessage: 'readable',
        multiDeleteService: 'readable',
        usersTableService: 'readable',
        // page-level config globals injected by forms_form.twig (form designer)
        groupsList: 'readable',
        formAndListIds: 'readable',
        // page-level config globals injected by theme-selector-with-form.twig
        themeSelectorTranslation: 'readable',
        customCSSPresetsPrefix: 'readable',
        geolocationHelper: 'readable',
        // page-level config global injected by aceditor.twig (the actions palette)
        actionsBuilderData: 'readable',
        // page-level config globals injected by doc.twig
        locale: 'readable',
        baseUrl: 'readable',
        i18n: 'readable',
        extensions: 'readable',
        // vendored libraries with a global entry point (javascripts/vendor/)
        FullCalendar: 'readable',
        opening_hours: 'readable',
        // Ace's generated modes end on a CommonJS interop guard (`typeof module == 'object'`),
        // dead in the browser but not ours to rewrite -- javascripts/mode-yeswiki.js.
        module: 'writable',
        // page-level config globals injected by reactions templates
        blockReactionRemove: 'readable',
        blockReactionRemoveMessage: 'readable',
        Html5Qrcode: 'readable',
        Html5QrcodeSupportedFormats: 'readable',
        // p5.js "global mode" API, used by javascripts/qrcodetroc-visualisation.js
        p5: 'readable',
        resizeCanvas: 'readable',
        createCanvas: 'readable',
        random: 'readable',
        color: 'readable',
        width: 'readable',
        height: 'readable',
        sin: 'readable',
        cos: 'readable',
        noStroke: 'readable',
        noFill: 'readable',
        fill: 'readable',
        stroke: 'readable',
        ellipse: 'readable',
        rect: 'readable',
        line: 'readable',
        dist: 'readable',
        mouseX: 'readable',
        mouseY: 'readable',
        textAlign: 'readable',
        text: 'readable',
        background: 'readable',
        CENTER: 'readable',
        LEFT: 'readable',
      },

      ecmaVersion: 13,
      sourceType: 'module',
    },

    // Beyond `recommended`: the handful this codebase has actually been bitten by, and which
    // its `eslint-disable` comments name -- a rule that is off makes every disable of it a
    // stale directive, which ESLint 9 then warns about in turn.
    rules: {
      eqeqeq: ['error', 'smart'],
      // Plain, NOT airbnb's `props: true`. The two catch different things, and only one of
      // them is a bug class here.
      //
      // Reassigning the parameter itself hides the argument the caller passed: the rest of the
      // function reads `str` and gets something else. There were three (`documentation.js`,
      // `search.js`, `map-geolocation-helper.js`), all now holding their working value in a
      // local, which is what the code meant.
      //
      // `props: true` reports writing to a *property* of a parameter, and that is the normal
      // idiom in this codebase rather than a mistake: 43 of the 110 it flagged are a Vue
      // transition component setting `el.style.height` -- which IS the transition API -- 16
      // decorate revision objects in place, and 3 are AMD's own `exports.Mode = Mode`. With 45
      // pre-existing disables already in the tree, turning it on means 155 suppression sites.
      // A rule silenced 155 times enforces nothing; it only trains people to add the comment.
      'no-param-reassign': 'error',
      // A list, not a bare 'error' -- the rule restricts nothing without one. `event` is the
      // one that bites: the implicit `window.event` looks like the handler's parameter and is
      // not, so code that reads it works until it is called any other way.
      'no-restricted-globals': ['error', 'event', 'isNaN', 'isFinite'],
      'no-eval': 'error',
      // `recommended` already turns this on; the one addition is `argsIgnorePattern`. Most
      // unused parameters here are simply gone now, but a few must keep their arity because
      // something else owns the signature -- Ace's `getNextLineIndent(state, line, tab)`, the
      // AMD `(require, exports, module)` wrapper, an abstract method a sub-component
      // overrides. `_name` is how those say "required by the caller, unused here".
      'no-unused-vars': ['error', { argsIgnorePattern: '^_' }],

      // Deliberately NOT enabled, though airbnb had them and a first pass here did too:
      //
      //   no-underscore-dangle   the leading underscore is this project's mark for a global
      //                          it owns (`_bazarDynamicComponents`) -- and for third-party
      //                          keys it does not (`_umap_options`). A convention, chosen
      //                          against.
      //   no-alert               21 deliberate `confirm()`/`alert()` calls, mostly "are you
      //                          sure" before something destructive. A rule disabled 21 times
      //                          enforces nothing; it is ritual.
      //   no-await-in-loop       one sequential import loop, where sequential is the intent.
      //
      // None is a bug class. Adding rules an existing codebase has already decided against,
      // as a side effect of changing formatter, would be 54 edits that improve nothing.
    },
  },
])
