<?php

//ATTENTION CE FICHIER DOIT ETRE ENCODE EN ISO-8859-1 sous peine de 
//voire des caractère bizarre dans les wikis.

/***********************************************************************
 * Pour générer ce fichier en cas de nouvelle version de wikini, exporter
 * la base d'un wiki fraichement installé et remplacer le préfixe des
 * tables par ".$table_prefix." mettre chaque requette une cellule du 
 * tableau listQuery
 */


 
$date = date("Y-m-d H:i:s");

$listQuery = array(
"CREATE TABLE IF NOT EXISTS `".$table_prefix."acls` (
  `page_tag` varchar(50) NOT NULL DEFAULT '',
  `privilege` varchar(20) NOT NULL DEFAULT '',
  `list` text NOT NULL,
  PRIMARY KEY (`page_tag`,`privilege`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;",

"CREATE TABLE IF NOT EXISTS `".$table_prefix."links` (
  `from_tag` char(50) NOT NULL DEFAULT '',
  `to_tag` char(50) NOT NULL DEFAULT '',
  UNIQUE KEY `from_tag` (`from_tag`,`to_tag`),
  KEY `idx_from` (`from_tag`),
  KEY `idx_to` (`to_tag`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;",

"INSERT INTO `".$table_prefix."links` (`from_tag`, `to_tag`) VALUES
('Accueil', 'Accueil'),
('Accueil', 'AdministrationDeWikiNi'),
('Accueil', 'AideWikiNi'),
('Accueil', 'DerniersChangements'),
('Accueil', 'DerniersCommentaires'),
('Accueil', 'PagesACreer'),
('Accueil', 'PagesOrphelines'),
('Accueil', 'ParametresUtilisateur'),
('Accueil', 'PremiersPasSurLeWiki'),
('Accueil', 'RechercheTexte'),
('Accueil', 'ReglesDeFormatage'),
('Accueil', 'TableauDeBordDeCeWiki'),
('Accueil', 'WikiAdmin'),
('ActionBacklinks', 'Accueil'),
('ActionBacklinks', 'ActionBacklinks'),
('ActionBacklinks', 'DerniersChangements'),
('ActionBacklinks', 'DerniersCommentaires'),
('ActionBacklinks', 'ParametresUtilisateur'),
('ActionBacklinks', 'TableauDeBordDeCeWiki'),
('ActionBacklinks', 'WikiAdmin'),
('ActionChangeStyle', 'Accueil'),
('ActionChangeStyle', 'ActionChangeStyle'),
('ActionChangeStyle', 'DerniersChangements'),
('ActionChangeStyle', 'DerniersCommentaires'),
('ActionChangeStyle', 'ParametresUtilisateur'),
('ActionChangeStyle', 'WikiAdmin'),
('ActionEraseSpamedComments', 'Accueil'),
('ActionEraseSpamedComments', 'ActionEraseSpamedComments'),
('ActionEraseSpamedComments', 'DerniersChangements'),
('ActionEraseSpamedComments', 'DerniersCommentaires'),
('ActionEraseSpamedComments', 'ParametresUtilisateur'),
('ActionEraseSpamedComments', 'WikiAdmin'),
('ActionInclude', 'Accueil'),
('ActionInclude', 'ActionInclude'),
('ActionInclude', 'DerniersChangements'),
('ActionInclude', 'DerniersCommentaires'),
('ActionInclude', 'PagePrincipale'),
('ActionInclude', 'ParametresUtilisateur'),
('ActionInclude', 'WikiAdmin'),
('ActionListPages', 'Accueil'),
('ActionListPages', 'ActionListPages'),
('ActionListPages', 'ActionPageIndex'),
('ActionListPages', 'DerniersChangements'),
('ActionListPages', 'DerniersCommentaires'),
('ActionListPages', 'IndexDesPages'),
('ActionListPages', 'ParametresUtilisateur'),
('ActionListPages', 'PlanDuSite'),
('ActionListPages', 'WikiAdmin'),
('ActionListUsers', 'Accueil'),
('ActionListUsers', 'ActionListUsers'),
('ActionListUsers', 'DerniersChangements'),
('ActionListUsers', 'DerniersCommentaires'),
('ActionListUsers', 'ParametresUtilisateur'),
('ActionListUsers', 'WikiAdmin'),
('ActionOrphanedPages', 'Accueil'),
('ActionOrphanedPages', 'ActionOrphanedPages'),
('ActionOrphanedPages', 'DerniersChangements'),
('ActionOrphanedPages', 'DerniersCommentaires'),
('ActionOrphanedPages', 'PagesOrphelines'),
('ActionOrphanedPages', 'ParametresUtilisateur'),
('ActionOrphanedPages', 'WikiAdmin'),
('ActionPageIndex', 'Accueil'),
('ActionPageIndex', 'ActionListPages'),
('ActionPageIndex', 'ActionPageIndex'),
('ActionPageIndex', 'DerniersChangements'),
('ActionPageIndex', 'DerniersCommentaires'),
('ActionPageIndex', 'IndexDesPagesBis'),
('ActionPageIndex', 'ParametresUtilisateur'),
('ActionPageIndex', 'WikiAdmin'),
('ActionRecentChanges', 'Accueil'),
('ActionRecentChanges', 'ActionRecentChanges'),
('ActionRecentChanges', 'DerniersChangements'),
('ActionRecentChanges', 'DerniersCommentaires'),
('ActionRecentChanges', 'ParametresUtilisateur'),
('ActionRecentChanges', 'WikiAdmin'),
('ActionRecentlyCommented', 'Accueil'),
('ActionRecentlyCommented', 'ActionRecentlyCommented'),
('ActionRecentlyCommented', 'DerniersChangements'),
('ActionRecentlyCommented', 'DerniersCommentaires'),
('ActionRecentlyCommented', 'ParametresUtilisateur'),
('ActionRecentlyCommented', 'WikiAdmin'),
('ActionRedirect', 'Accueil'),
('ActionRedirect', 'ActionRedirect'),
('ActionRedirect', 'DerniersChangements'),
('ActionRedirect', 'DerniersCommentaires'),
('ActionRedirect', 'PagePrincipale'),
('ActionRedirect', 'ParametresUtilisateur'),
('ActionRedirect', 'WikiAdmin'),
('ActionTextSearch', 'Accueil'),
('ActionTextSearch', 'ActionTextSearch'),
('ActionTextSearch', 'DerniersChangements'),
('ActionTextSearch', 'DerniersCommentaires'),
('ActionTextSearch', 'MotWiki'),
('ActionTextSearch', 'ParametresUtilisateur'),
('ActionTextSearch', 'RechercheTexte'),
('ActionTextSearch', 'WikiAdmin'),
('ActionTrail', 'Accueil'),
('ActionTrail', 'ActionTrail'),
('ActionTrail', 'DerniersChangements'),
('ActionTrail', 'DerniersCommentaires'),
('ActionTrail', 'Page1'),
('ActionTrail', 'Page2'),
('ActionTrail', 'Page3'),
('ActionTrail', 'Page31'),
('ActionTrail', 'Page32'),
('ActionTrail', 'Page4'),
('ActionTrail', 'Page5'),
('ActionTrail', 'Page6'),
('ActionTrail', 'ParametresUtilisateur'),
('ActionTrail', 'WikiAdmin'),
('ActionUserSettings', 'Accueil'),
('ActionUserSettings', 'ActionUserSettings'),
('ActionUserSettings', 'DerniersChangements'),
('ActionUserSettings', 'DerniersCommentaires'),
('ActionUserSettings', 'ParametresUtilisateur'),
('ActionUserSettings', 'WikiAdmin'),
('ActionWantedPages', 'Accueil'),
('ActionWantedPages', 'ActionWantedPages'),
('ActionWantedPages', 'DerniersChangements'),
('ActionWantedPages', 'DerniersCommentaires'),
('ActionWantedPages', 'MotWiki'),
('ActionWantedPages', 'PagesACreer'),
('ActionWantedPages', 'ParametresUtilisateur'),
('ActionWantedPages', 'WikiAdmin'),
('AdministrationDeWikiNi', 'Accueil'),
('AdministrationDeWikiNi', 'ActionEditActionsACLs'),
('AdministrationDeWikiNi', 'ActionEditGroups'),
('AdministrationDeWikiNi', 'ActionEditHandlersACLs'),
('AdministrationDeWikiNi', 'AdministrationDeWikiNi'),
('AdministrationDeWikiNi', 'ControlerLAccesAuxPages'),
('AdministrationDeWikiNi', 'DerniersChangements'),
('AdministrationDeWikiNi', 'DerniersCommentaires'),
('AdministrationDeWikiNi', 'ParametresUtilisateur'),
('AdministrationDeWikiNi', 'SuppressionDePage'),
('AdministrationDeWikiNi', 'WikiAdmin'),
('AdministrationDeWikiNi', 'WikiNi'),
('AidE', 'Accueil'),
('AidE', 'AidE'),
('AidE', 'ControlerLAccesAuxPages'),
('AidE', 'CoursUtilisationYesWiki'),
('AidE', 'DerniersChangements'),
('AidE', 'DerniersCommentaires'),
('AidE', 'ListeDesActionsWikini'),
('AidE', 'ParametresUtilisateur'),
('AidE', 'ReglesDeFormatage'),
('AidE', 'WikiAdmin'),
('AideWikiNi', 'Accueil'),
('AideWikiNi', 'AideWikiNi'),
('AideWikiNi', 'ControlerLAccesAuxPages'),
('AideWikiNi', 'DerniersChangements'),
('AideWikiNi', 'DerniersCommentaires'),
('AideWikiNi', 'ListeDesActionsWikini'),
('AideWikiNi', 'ParametresUtilisateur'),
('AideWikiNi', 'ReglesDeFormatage'),
('AideWikiNi', 'WikiAdmin'),
('BacASable', 'Accueil'),
('BacASable', 'BacASable'),
('BacASable', 'DerniersChangements'),
('BacASable', 'DerniersCommentaires'),
('BacASable', 'ParametresUtilisateur'),
('BacASable', 'WikiAdmin'),
('ControlerLAccesAuxPages', 'Accueil'),
('ControlerLAccesAuxPages', 'ControlerLAccesAuxPages'),
('ControlerLAccesAuxPages', 'DerniersChangements'),
('ControlerLAccesAuxPages', 'DerniersCommentaires'),
('ControlerLAccesAuxPages', 'ParametresUtilisateur'),
('ControlerLAccesAuxPages', 'WikiAdmin'),
('CoursUtilisationYesWiki', 'Accueil'),
('CoursUtilisationYesWiki', 'CoursUtilisationYesWiki'),
('CoursUtilisationYesWiki', 'DerniersChangements'),
('CoursUtilisationYesWiki', 'DerniersChangementsRSS'),
('CoursUtilisationYesWiki', 'DerniersCommentaires'),
('CoursUtilisationYesWiki', 'JamesBond'),
('CoursUtilisationYesWiki', 'ListeDesActionsWikini'),
('CoursUtilisationYesWiki', 'PageFooter'),
('CoursUtilisationYesWiki', 'PageHeader'),
('CoursUtilisationYesWiki', 'PageMenu'),
('CoursUtilisationYesWiki', 'PageMenuHaut'),
('CoursUtilisationYesWiki', 'PageRapideHaut'),
('CoursUtilisationYesWiki', 'PagesOrphelines'),
('CoursUtilisationYesWiki', 'ParametresUtilisateur'),
('CoursUtilisationYesWiki', 'ReglesDeFormatage'),
('CoursUtilisationYesWiki', 'TableauDeBordDeCeWiki'),
('CoursUtilisationYesWiki', 'WikiAdmin'),
('CoursUtilisationYesWiki', 'YesWiki'),
('DerniersChangements', 'Accueil'),
('DerniersChangements', 'DerniersChangements'),
('DerniersChangements', 'DerniersCommentaires'),
('DerniersChangements', 'ParametresUtilisateur'),
('DerniersChangements', 'WikiAdmin'),
('DerniersChangementsRSS', 'Accueil'),
('DerniersChangementsRSS', 'DerniersChangements'),
('DerniersChangementsRSS', 'DerniersChangementsRSS'),
('DerniersChangementsRSS', 'DerniersCommentaires'),
('DerniersChangementsRSS', 'ParametresUtilisateur'),
('DerniersChangementsRSS', 'WikiAdmin'),
('DerniersCommentaires', 'Accueil'),
('DerniersCommentaires', 'DerniersChangements'),
('DerniersCommentaires', 'DerniersCommentaires'),
('DerniersCommentaires', 'ParametresUtilisateur'),
('DerniersCommentaires', 'WikiAdmin'),
('IndexDesPages', 'Accueil'),
('IndexDesPages', 'DerniersChangements'),
('IndexDesPages', 'DerniersCommentaires'),
('IndexDesPages', 'IndexDesPages'),
('IndexDesPages', 'ParametresUtilisateur'),
('IndexDesPages', 'WikiAdmin'),
('IndexDesPagesBis', 'Accueil'),
('IndexDesPagesBis', 'DerniersChangements'),
('IndexDesPagesBis', 'DerniersCommentaires'),
('IndexDesPagesBis', 'IndexDesPagesBis'),
('IndexDesPagesBis', 'ParametresUtilisateur'),
('IndexDesPagesBis', 'WikiAdmin'),
('ListeDesActionsWikini', 'Accueil'),
('ListeDesActionsWikini', 'ActionBacklinks'),
('ListeDesActionsWikini', 'ActionChangeStyle'),
('ListeDesActionsWikini', 'ActionEraseSpamedComments'),
('ListeDesActionsWikini', 'ActionFindpage'),
('ListeDesActionsWikini', 'ActionInclude'),
('ListeDesActionsWikini', 'ActionListPages'),
('ListeDesActionsWikini', 'ActionListUsers'),
('ListeDesActionsWikini', 'ActionMyChanges'),
('ListeDesActionsWikini', 'ActionMyPages'),
('ListeDesActionsWikini', 'ActionOrphanedPages'),
('ListeDesActionsWikini', 'ActionPageIndex'),
('ListeDesActionsWikini', 'ActionRecentChanges'),
('ListeDesActionsWikini', 'ActionRecentChangesRSS'),
('ListeDesActionsWikini', 'ActionRecentComments'),
('ListeDesActionsWikini', 'ActionRecentlyCommented'),
('ListeDesActionsWikini', 'ActionRedirect'),
('ListeDesActionsWikini', 'ActionTextSearch'),
('ListeDesActionsWikini', 'ActionTrail'),
('ListeDesActionsWikini', 'ActionUserSettings'),
('ListeDesActionsWikini', 'ActionWantedPages'),
('ListeDesActionsWikini', 'DerniersChangements'),
('ListeDesActionsWikini', 'DerniersCommentaires'),
('ListeDesActionsWikini', 'ListeDesActionsWikini'),
('ListeDesActionsWikini', 'ParametresUtilisateur'),
('ListeDesActionsWikini', 'WikiAdmin'),
('MotWiki', 'Accueil'),
('MotWiki', 'DerniersChangements'),
('MotWiki', 'DerniersCommentaires'),
('MotWiki', 'MotWiki'),
('MotWiki', 'ParametresUtilisateur'),
('MotWiki', 'WikiAdmin'),
('NomWiki', 'Accueil'),
('NomWiki', 'DerniersChangements'),
('NomWiki', 'DerniersCommentaires'),
('NomWiki', 'NomWiki'),
('NomWiki', 'ParametresUtilisateur'),
('NomWiki', 'WikiAdmin'),
('PageColonneDroite', 'Accueil'),
('PageColonneDroite', 'DerniersChangements'),
('PageColonneDroite', 'DerniersCommentaires'),
('PageColonneDroite', 'PageColonneDroite'),
('PageColonneDroite', 'ParametresUtilisateur'),
('PageColonneDroite', 'WikiAdmin'),
('PageFooter', 'Accueil'),
('PageFooter', 'DerniersChangements'),
('PageFooter', 'DerniersCommentaires'),
('PageFooter', 'PageFooter'),
('PageFooter', 'ParametresUtilisateur'),
('PageFooter', 'WikiAdmin'),
('PageHeader', 'Accueil'),
('PageHeader', 'DerniersChangements'),
('PageHeader', 'DerniersCommentaires'),
('PageHeader', 'PageHeader'),
('PageHeader', 'ParametresUtilisateur'),
('PageHeader', 'WikiAdmin'),
('PageMenu', 'Accueil'),
('PageMenu', 'DerniersChangements'),
('PageMenu', 'DerniersCommentaires'),
('PageMenu', 'PageMenu'),
('PageMenu', 'ParametresUtilisateur'),
('PageMenu', 'WikiAdmin'),
('PageMenuHaut', 'Accueil'),
('PageMenuHaut', 'DerniersChangements'),
('PageMenuHaut', 'DerniersCommentaires'),
('PageMenuHaut', 'PageMenuHaut'),
('PageMenuHaut', 'ParametresUtilisateur'),
('PageMenuHaut', 'WikiAdmin'),
('PageRapideHaut', 'Accueil'),
('PageRapideHaut', 'AidE'),
('PageRapideHaut', 'DerniersChangements'),
('PageRapideHaut', 'DerniersCommentaires'),
('PageRapideHaut', 'PageRapideHaut'),
('PageRapideHaut', 'ParametresUtilisateur'),
('PageRapideHaut', 'TableauDeBordDeCeWiki'),
('PageRapideHaut', 'WikiAdmin'),
('PagesACreer', 'Accueil'),
('PagesACreer', 'DerniersChangements'),
('PagesACreer', 'DerniersCommentaires'),
('PagesACreer', 'PagesACreer'),
('PagesACreer', 'ParametresUtilisateur'),
('PagesACreer', 'WikiAdmin'),
('PagesOrphelines', 'Accueil'),
('PagesOrphelines', 'DerniersChangements'),
('PagesOrphelines', 'DerniersCommentaires'),
('PagesOrphelines', 'PagesOrphelines'),
('PagesOrphelines', 'ParametresUtilisateur'),
('PagesOrphelines', 'WikiAdmin'),
('ParametresUtilisateur', 'Accueil'),
('ParametresUtilisateur', 'DerniersChangements'),
('ParametresUtilisateur', 'DerniersCommentaires'),
('ParametresUtilisateur', 'ParametresUtilisateur'),
('ParametresUtilisateur', 'WikiAdmin'),
('PlanDuSite', 'Accueil'),
('PlanDuSite', 'DerniersChangements'),
('PlanDuSite', 'DerniersCommentaires'),
('PlanDuSite', 'ParametresUtilisateur'),
('PlanDuSite', 'PlanDuSite'),
('PlanDuSite', 'WikiAdmin'),
('PremiersPasSurLeWiki', 'Accueil'),
('PremiersPasSurLeWiki', 'BacASable'),
('PremiersPasSurLeWiki', 'DerniersChangements'),
('PremiersPasSurLeWiki', 'DerniersCommentaires'),
('PremiersPasSurLeWiki', 'MotWiki'),
('PremiersPasSurLeWiki', 'ParametresUtilisateur'),
('PremiersPasSurLeWiki', 'PremiersPasSurLeWiki'),
('PremiersPasSurLeWiki', 'ReglesDeFormatage'),
('PremiersPasSurLeWiki', 'WikiAdmin'),
('RechercheTexte', 'Accueil'),
('RechercheTexte', 'DerniersChangements'),
('RechercheTexte', 'DerniersCommentaires'),
('RechercheTexte', 'ParametresUtilisateur'),
('RechercheTexte', 'RechercheTexte'),
('RechercheTexte', 'WikiAdmin'),
('ReglesDeFormatage', 'Accueil'),
('ReglesDeFormatage', 'BacASable'),
('ReglesDeFormatage', 'DerniersChangements'),
('ReglesDeFormatage', 'DerniersCommentaires'),
('ReglesDeFormatage', 'ParametresUtilisateur'),
('ReglesDeFormatage', 'ReglesDeFormatage'),
('ReglesDeFormatage', 'WikiAdmin'),
('TableauDeBordDeCeWiki', 'Accueil'),
('TableauDeBordDeCeWiki', 'DerniersChangements'),
('TableauDeBordDeCeWiki', 'DerniersCommentaires'),
('TableauDeBordDeCeWiki', 'IndexDesPages'),
('TableauDeBordDeCeWiki', 'IndexDesPagesBis'),
('TableauDeBordDeCeWiki', 'PagesACreer'),
('TableauDeBordDeCeWiki', 'PagesOrphelines'),
('TableauDeBordDeCeWiki', 'ParametresUtilisateur'),
('TableauDeBordDeCeWiki', 'PlanDuSite'),
('TableauDeBordDeCeWiki', 'TableauDeBordDeCeWiki'),
('TableauDeBordDeCeWiki', 'WikiAdmin');",

"CREATE TABLE IF NOT EXISTS `".$table_prefix."pages` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `tag` varchar(50) NOT NULL DEFAULT '',
  `time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `body` text NOT NULL,
  `body_r` text NOT NULL,
  `owner` varchar(50) NOT NULL DEFAULT '',
  `user` varchar(50) NOT NULL DEFAULT '',
  `latest` enum('Y','N') NOT NULL DEFAULT 'N',
  `handler` varchar(30) NOT NULL DEFAULT 'page',
  `comment_on` varchar(50) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `idx_tag` (`tag`),
  KEY `idx_time` (`time`),
  KEY `idx_latest` (`latest`),
  KEY `idx_comment_on` (`comment_on`),
  FULLTEXT KEY `tag` (`tag`,`body`)
) ENGINE=MyISAM  AUTO_INCREMENT=45;",

"INSERT INTO `".$table_prefix."pages` (`id`, `tag`, `time`, `body`, `body_r`, `owner`, `user`, `latest`, `handler`, `comment_on`) VALUES
(1, 'ReglesDeFormatage', '$date', '==== Guide des règles de formatage ====\n\nLes règles de formatage avec Wakka diffèrent légèrement des autres Wikis. (Voir par exemple [[http://c2.com/cgi/wiki?TextFormattingRules les règles de formatage de WikiWikiWeb]], le premier Wiki connu.)\nTout texte placé entre deux guillemets doubles - \" - est présenté tel que.\n\nVous pouvez effectuer vos propres test dans le BacASable : c''est un endroit fait pour ça.\n\nRègles de base :\n	\"\"**Texte en gras !** ---\"\"> **Texte en gras !**\n	\"\"//Texte en italique.// ---\"\"> //Texte en italique.//\n	\"\"Texte __souligné__ ! ---\"\"> Texte __souligné__ !\n	\"\"Texte @@barré@@ ! ---\"\"> Texte @@barré@@ !\n	\"\"##texte à espacement fixe## ---\"\"> ##texte à espacement fixe##\n	\"\"%%code%%\"\"\n	\"\"%%(php) PHP code%%\"\"\n	\"\"%%(delphi) code delphi/pascal%%\"\"\n\nEmpêcher le formatage du texte :\n        Pour empêcher que Wikini n''interprète les balises de formatage de texte qu''il reconnait, encadrer le texte par une paire de guillemets doubles. \"\"Par __exemple__, ce **texte** @@contient@@ des %%balises%% reconnue par Wikini qui ne sont //pas// interprétée car il est encadré par une paire de **guillemets double** comme __vous__ pouvez vous en apercevoir :)\"\"\n        Deux autres utilisations :\n        - écrire directement du HTML dans le wikini - par exemple pour les tableaux... ;-) - vu que ce qui est renvoyé est tout de même interprété par le moteur de rendu de Mozilla\n        - afficher des logs / des scripts shell en ajoutant les tag <pre> et </pre> qui seront interprétés pour afficher le texte tel quel par le navigateur (sous réserve qu''il n''y ait pas de double guillemet dedans). Cela permet d''avoir le contenu in extenso plutôt que dans une boîte de code qui est de taille fixe (contrairement à la fonctionnalité de phpBB2 avec les tags [code] et [/code])\n\nLiens forcés :\n	\"\"[[http://www.mon-site.org]]\"\"\n	\"\"[[http://www.mon-site.org Mon-site]]\"\"\n	\"\"[[P2P]]\"\"\n	\"\"[[P2P Page sur le P2P]]\"\"\n\nEn-têtes :\n	\"\"====== En-tête énorme ======\"\" ====== En-tête énorme ======\n	\"\"===== En-tête très gros =====\"\" ===== En-tête très gros =====\n	\"\"==== En-tête gros ====\"\" ==== En-tête gros ====\n	\"\"=== En-tête normal ===\"\" === En-tête normal ===\n	\"\"== Petit en-tête ==\"\" == Petit en-tête ==\n\nSéparateur horizontal : il suffit de taper au moins 4 \"-\", au dela de 4 tirets c''est le meme effet\nExemple :  \"\"----\"\"\n-------\n\n\nRetour de ligne forcé :\n	\"\"---\"\"\n\nL''indentation de textes se fait avec la touche \"TAB\". Vous pouvez aussi créer des listes à puces ou numérotées :\n	\"\"- liste à puce\"\"\n	\"\"1) liste numérotée (chiffres arabes)\"\"\n	\"\"A) liste numérotée (capitales alphabétiques)\"\"\n	\"\"a) liste numérotée (minuscules alphabétiques)\"\"\n	\"\"i) liste numérotée (chiffres romains)\"\"\n\nVous pouvez également indenter du texte en utilisant des caractères espace au lieu de la touche \"TAB\", les exemples ci dessus restent valables mais attention à ne pas mélanger des \"TAB\" et des espaces dans la même énumération.\n\n        \"\"- liste à puce\"\"\n        \"\"1) liste numérotée (chiffres arabes)\"\"\n        \"\"A) liste numérotée (capitales alphabétiques)\"\"\n        \"\"a) liste numérotée (minuscules alphabétiques)\"\"\n        \"\"i) liste numérotée (chiffres romains)\"\"\n\nNote : à cause d''un [[http://bugzilla.mozilla.org/show_bug.cgi?id=10547 bogue dans son moteur de rendu]], les listes, utilisant la touche TAB, ne fonctionnent pas (encore) sous Mozilla.\n\n', '', 'WikiAdmin', 'WikiAdmin', 'Y', 'page', ''),
(2, 'ActionRecentlyCommented', '$date', 'L''action \"\"{{RecentlyCommented}}\"\" permet d''afficher la liste des pages ayant été récement commentées. Cette action est visible sur la page DerniersCommentaires.\n\n==== Paramètres ====\nCette action accepte un seul paramètre, le paramètre \"max\" permettant de spécifier le nombre maximum de pages récemment commentées à afficher.\nPar exemple \"\"{{RecentlyCommented max=\"3\"}}\"\" va donner le résultat suivant :\n\n{{RecentlyCommented max=\"3\"}}\n\n----\n{{trail toc=\"ListeDesActionsWikini\"}}\n', '', 'WikiAdmin', 'WikiAdmin', 'Y', 'page', ''),
(3, 'PlanDuSite', '$date', '{{listpages/tree}}', '', 'WikiAdmin', 'WikiAdmin', 'Y', 'page', ''),
(4, 'ActionRedirect', '$date', 'L''action ##\"\"{{redirect page=\"PagePrincipale\"}}\"\"## permet d''être redirigé vers une autre page lorsqu''une page est demandée (ici vers la PagePrincipale). Cela permet de faire des \"alias\" de page, plusieurs noms différents pour une même page.\n\n**Synthèse des cas** où cette action peut être utile :\n - dans le cas où certains termes sont d''orthographe variable, comme par exemple Persistance of Vision - qui devient \"\"PoV\"\", \"\"POV\"\", \"\"PovRay\"\", \"\"POV-Ray\"\"... et certains Wiki voient donc deux pages apparaitre pour la même chose, avec du contenu trop élaboré pour être facilement reconciliable en une seule page.\n - en cas de renommage d''une page (en fait le déplacement d''une page vers une autre page), l''ancien nom peut rediriger vers le nouveau nom ; ceci peut être particulièrement utile dans le cas où de très nombreuses pages pointe sur la page originelle, évitant ainsi de changer les liens dans chaque page\n - redirection d''une page au nom wiki disgracieux vers une page au nom wiki plus lisible ; exemples : \"\"SpIp\"\" => Spip, \"\"DelPhine\"\" => Delphine, etc.\n\nUne différence notable entre une inclusion et une redirection : lors d''une inclusion, le contenu de la page incluant une autre page peut être modifé, donc utiliser l''inclusion pour faire des alias de page ne me parait pas très sûr car il risque d''apparaitre des divergences de contenu si c''est la page incluant une autre page qui est modifée. Par contre, une redirection __impose__ qu''une seule page est éditable et la cohérence de contenu est donc correcte.\n\n===== Paramètres =====\n\nCette action accepte un seul paramètre :\n  - page : paramètre obligatoire pour désigner la page vers laquelle la page est redirigée.\n\n===== Modification d''une page contenant l''action ##redirect## =====\nIl faut entrer manuellement dans la barre d''adresse du navigateur l''adresse de la page + le \"handler\" désiré ; par exemple :\nPour la modifier :\n    - http://domaine/wakka.php?wiki=NomDeLaPage/edit\nPour la supprimer :\n    - http://domaine/wakka.php?wiki=NomDeLaPage/deletepage\n\n----\n{{trail toc=\"ListeDesActionsWikini\"}}\n', '', 'WikiAdmin', 'WikiAdmin', 'Y', 'page', ''),
(5, 'MotWiki', '$date', '{{redirect page=\"NomWiki\"}}\n', '', 'WikiAdmin', 'WikiAdmin', 'Y', 'page', ''),
(6, 'ActionBacklinks', '$date', 'Action permettant d''insérer la liste de toutes les pages faisant référence à la page courante. Dans cette présente page, \"\"{{backlinks}}\"\" donne ceci :\n\n{{BackLinks}}\n\nSur la page personnelle d''un utilisateur, cette action affichera aussi les pages dont il est le propriétaire ou le dernier modificateur.\n\n===== Paramètres =====\n\n==== Paramètre \"page\" ====\nLe paramètre \"page\" ([[http://www.wikini.net WikiNi]] >= 0.4.1) permet de spécifier une page différente de la page courante.\nPar exemple ##\"\"{{backlinks page=\"PagePrincipale\"}}\"\"##\nCe paramètre peut être utile, par exemple :\n  - pour améliorer le TableauDeBordDeCeWiki : il suffit d''ajouter la liste des pages liées à la page \"\"AFaire\"\" pour connaître les pages qui doivent faire l''objet d''un travail\n  - pour consolider des données sur une seule page : par exemple la liste des pages liées aux pages \"\"EstUnHomme\"\" et \"\"EstUneFemme\"\"\n  - autres ?\n\n==== Paramètre \"exclude\" ====\nLe paramètre \"exclude\" ([[http://www.wikini.net WikiNi]] >= 0.4.1) permet de spécifier des pages à exclure de la liste des pages qui ont pourtant un lien vers la page de référence.\nIl est en effet parfois génant d''afficher la totalité des pages faisant référence à une page. Par exemple, la page \"\"AFaire\"\" liste la page \"\"CharlesNepoteVeilleSurInternet\"\" alors que, non seulement cette information n''a pas d''intérêt mais elle pollue en outre la lecture de cette page. Autre exemple, une page \"\"MamiFeres\"\" a intérêt par exemple à lister \"\"CheVal\"\" et \"\"ElePhant\"\" mais pas nécessairement \"\"AniMaux\"\" qui est une catégorie supérieure. Je suggère donc la création d''un paramètre exclude destiné à exclure certaines pages : par exemple :\n##\"\"{{backlinks exclude=\"AniMaux\"}}\"\"##\nLe paramètre \"exclude\" peut contenir plusieurs noms de page séparés par des \";\", par exemple : ##\"\"{{backlinks exclude=\"AniMaux; PagePrincipale\"}}\"\"##\n\n----\n{{trail toc=\"ListeDesActionsWikini\"}}', '', 'WikiAdmin', 'WikiAdmin', 'Y', 'page', ''),
(7, 'PagesOrphelines', '$date', '{{OrphanedPages}}', '', 'WikiAdmin', 'WikiAdmin', 'Y', 'page', ''),
(8, 'ActionInclude', '$date', 'L''action ##\"\"{{include page=\"PagePrincipale\"}}\"\"## ([[http://www.wikini.net WikiNi]] >= 0.4.1) permet d''inclure dans une page une autre page du wiki (ici la page PagePrincipale). Cette action possède plusieurs applications :\n  - Regrouper plusieurs pages en une seule et par exemple, créer un document à partir de différentes \"sections\" disséminées dans plusieurs pages ;\n  - Commenter/critiquer une page en lecture seule\n    (en l''incluant dans le corps d''une autre page)\n  - Constituer des blocs d''informations redondantes qui seront répétés (incluses) dans plusieurs autres pages\n    (il peut s''agir d''un menu, d''une signature, d''une mention légale, ou autre)\n  - Configurer le menu de navigation de [[http://www.wikini.net WikiNi]]\n    (en indiquant ##\"navigation_links\" => \"\"\"{{include page=\\\"MenuDuHaut\\\"}}\"\"\",## dans le fichier wakka.config.php. La page \"\"MenuDuHaut\"\", optionnellement protégée en écriture, contiendra le menu qui sera affiché.)\n  - Réaliser une sorte de syndication\n    (en incluant des pages d''un autre __\"\"WikiNi\"\"__)\n\n==== Paramètres ====\nCette action accepte deux paramètres :\n  - //page// (paramètre obligatoire) : désigne la page à inclure. Ce paramètre peut être une page locale au [[http://www.wikini.net WikiNi]] ou une page d''un autre [[http://www.wikini.net WikiNi]].\n  - //class// (paramètre optionnel) : désignant un ou plusieurs éléments de style qui seront combinés pour déterminer l''aspect que prendra la page incluse.\n\nLe paramètre //class// liste un ou plusieurs éléments de style, séparés par des espaces. Les éléments possibles sont les suivants :\n - **right** : bloc flotant à droite ##{ float: right; width: 17%; }##\n - **left** : bloc flotant à gauche ##{ float: left; width: 17%; }##\n - **solid_border** : encadré noir ##{ border: solid; padding: 2px; }##\n - **gray_background** : fond gris ##{ background-color: #DDDDDD; }##\n - **small_fonts** : petites polices ##{ font-size: 0.8em; }##\n - **big_fonts** : grandes polces ##{ font-size: 1.2em; }##\n - **height10em** : boite d''une hauteur de 10 lignes de texte, avec ascenseur ##{ height: 10em; overflow: scroll; }##\n - **height15em** : boite d''une hauteur de 15 lignes de texte, avec ascenseur ##{ height: 15em; overflow: scroll; }##\n - **height30em** : boite d''une hauteur de 30 lignes de texte, avec ascenseur ##{ height: 30em; overflow: scroll; }##\n - **height60em** : boite d''une hauteur de 60 lignes de texte, avec ascenseur ##{ height: 60em; overflow: scroll; }##\n\n{{include page=\"ListeDesActionsWikini\" class=\"right height15em small_fonts solid_border gray_background\"}}\nLe paramètre //class// liste des éléments de style qui seront combinés. Par exemple, si l''on souhaite obtenir une boite grise avec une bordure et de petits caractères, on écrira : ##\"\"{{include page=\"ListeDesActionsWikini\" class=\"right height15em small_fonts solid_border gray_background\"}}\"\"## (voir le résultat dans le cadre ci-contre)\n\nSi le paramètre //class// est absent, le texte inclus sera présenté de manière non différenciée par rapport au reste de la page.\n\nUne page ne peut-être inclue dans elle-même. De même, une chaîne d''inclusion ne peut contenir deux fois la même page. Par ensmple, si la page Toto inclus la page Titi, et si la page Titi inclus la page Tata, alors ni la page Titi ni la page Tata ne peuvent inclure la page Toto, sans quoi une erreur sera produite.\n\n----\n{{trail toc=\"ListeDesActionsWikini\"}}\n', '', 'WikiAdmin', 'WikiAdmin', 'Y', 'page', ''),
(9, 'ActionListUsers', '$date', '==== Liste des comptes utilisateurs ====\n\nCette fonction permet de lister les comptes utilisateurs créés.\nLa fonction est loin d''être indispensable, mais elle permet, par exemple, de connaître les nouveaux utilisateurs qui se sont inscrits pour des raisons pratiques (paramétrage) mais qui n''ont pas encore renseigné leur page personnelle. Autre exemple, on peut observer le nombre de nouveaux inscrits suite à une promotion du site, etc.\nPar défaut, cette fonction donne la liste des comptes par ordre alphabétique. Cette fonction accepte en outre le paramètre \"last\" permettant le tri des comptes par odre inverse de date de création. Ce dernier paramètre accepte lui-même, de surcroit, un chiffre en paramètre permettant de réduire le nombre comptes affichés. La syntaxe d''utilisation de cette \"action\" est donnée ci-dessous.\n\n\"\"{{Listusers/last}}\"\" : donne la liste des derniers comptes utilisateurs\n{{listusers/last}}\n\n\"\"{{Listusers/last=\"3\"}}\"\"\n{{listusers/last=\"3\"}}\n\n\"\"{{Listusers/last=\"50\"}}\"\"\n{{listusers/last=\"50\"}}\n\n\"\"{{Listusers}}\"\" : donne la liste des comptes utilisateurs par ordre alphabétique\n{{listusers}}\n\n----\n{{trail toc=\"ListeDesActionsWikini\"}}\n', '', 'WikiAdmin', 'WikiAdmin', 'Y', 'page', ''),
(10, 'ActionRecentChanges', '$date', 'L''action \"\"{{RecentChanges}}\"\" affiche la liste des pages récement modifiées. Elle est illustrée dans la page DerniersChangements.\n\n==== Paramètres ====\nCette action prend en compte le paramètre \"max\", permettant à un utilisateur de spécifier le nombre de pages affichées.\nPar exemple \"\"{{recentchanges max=\"3\"}}\"\" donne :\n\n{{recentchanges max=\"3\"}}\n\n----\n{{trail toc=\"ListeDesActionsWikini\"}}\n', '', 'WikiAdmin', 'WikiAdmin', 'Y', 'page', ''),
(11, 'RechercheTexte', '$date', '{{TextSearch}}', '', 'WikiAdmin', 'WikiAdmin', 'Y', 'page', ''),
(12, 'AdministrationDeWikiNi', '$date', 'L''administration n''est pas une tâche absolument nécessaire et WikiNi peut être utilisé tel quel, directement après son installation.\n\nVous pouvez cependant vouloir :\n - étendre ou restreindre des droits à tout ou partie des utilisateurs\n - réaliser des opérations impossibles pour un utilisateur normal :\n   - nettoyer les spams\n   - octroyer les droits d''administration à d''autres utilisateurs\n   - modifier les droits d''accès à n''importe quelle page\n   - etc.\nVoyons l''étendue de ces possibilités.\n\n==== 1. Le groupe des administrateurs ====\nA l''installation de WikiNi, un compte utilisateur a été créé qui appartient au groupe \"admins\". Tous les membres de ce groupe ont tous les droits sur le wiki. **N''ajoutez à ce groupe que des personnes dont vous êtes sûrs.**\n\n==== 2. Ajout d''autres comptes au groupes des administrateur ====\nLe premier compte administrateur peut ajouter d''autres comptes au groupe des administrateurs, via l''action ##\"\"{{editgroups}}\"\"## (cf. ActionEditGroups).\n\n==== 3. Gestion des droits d''accès et suppression de pages ====\nLes administrateurs peuvent :\n - gérer les droits d''accès à toutes les pages\n - supprimer toute page\nCes opérations sont réalisées de la même manière que lorsqu''un utilisateur est propriétaire d''une page (cf. ControlerLAccesAuxPages et SuppressionDePage).\n\n==== 4. Gestion des droits d''accès aux actions et aux handlers ====\nLes membres du groupes \"admin\" sont les seuls à pouvoir gérer les droits d''accès aux actions et aux handlers. Pour cela, il faut utiliser les actions ##\"\"{{editactionsacls}}\"\"## et ##\"\"{{edithandlersacls}}\"\"## (cf. ActionEditActionsACLs et ActionEditHandlersACLs).\n**La gestion de ces droits doit être effectuée avec beaucoup de précaution.**\nNous vous renvoyons à la documentation générale pour connaître les possibilités offertes par chaque action et chaque handler.\n', '', 'WikiAdmin', 'WikiAdmin', 'Y', 'page', ''),
(13, 'ActionOrphanedPages', '$date', 'L''action \"\"{{OrphanedPages}}\"\" liste toutes les pages orphelines, c''est-à-dire toutes les pages n''étant reliées à aucune autre page.\nCette action est utilisée ici dans la page : PagesOrphelines.\n\nElle peut servir :\n - à localiser les pages qui ont besoin d''être reliées à d''autres pages\n - à localiser les pages rendues inutiles et que l''on peut alors effacer\n\nCette page ne comporte aucun paramètre.\n\n----\n{{trail toc=\"ListeDesActionsWikini\"}}\n', '', 'WikiAdmin', 'WikiAdmin', 'Y', 'page', ''),
(14, 'PagesACreer', '$date', '{{WantedPages}}', '', 'WikiAdmin', 'WikiAdmin', 'Y', 'page', ''),
(15, 'ActionTextSearch', '$date', 'L''action ##\"\"{{TextSearch}}\"\"## permet de lister les pages contenant un ou plusieurs mots entré(s) par l''utilisateur.\nOn peut la voir en action sur la page RechercheTexte.\n\nCette action utilise la fonction d''indexation en texte intégral de \"\"MySQL\"\" et hérite de ses qualités et défauts :\n - la recherche est quasi instantanée\n - la recherche est limitée à des mots de 4 lettres au minimim\n - la recherche n''accepte pas de caractères génériques (ou caractères joker : \".*?\", etc.)\n - la recherche n''est pas lématisée : la recherche de \"protocole\" ne trouvera pas \"protocoles\" ; la recherche de \"lascif\" ne trouvera pas \"lascive\"\n - la recherche n''est pas effectuée sur une partie de MotWiki : la recherche de \"text\" ne donnera pas ActionTextSearch pour résultat\n\n----\n{{trail toc=\"ListeDesActionsWikini\"}}\n', '', 'WikiAdmin', 'WikiAdmin', 'Y', 'page', ''),
(16, 'DerniersChangementsRSS', '$date', '{{recentchangesrss}}', '', 'WikiAdmin', 'WikiAdmin', 'Y', 'page', ''),
(17, 'Accueil', '$date', 'Bienvenue !\n\nCliquez sur le lien \"Editer cette page\" au bas de la page pour démarrer,\nou bien apprenez à faire vos PremiersPasSurLeWiki.\n\nPages utiles : PagesOrphelines, PagesACreer, RechercheTexte, ReglesDeFormatage, AideWikiNi, TableauDeBordDeCeWiki, AdministrationDeWikiNi.\n', '', 'WikiAdmin', 'WikiAdmin', 'Y', 'page', ''),
(18, 'DerniersCommentaires', '$date', '{{RecentlyCommented}}', '', 'WikiAdmin', 'WikiAdmin', 'Y', 'page', ''),
(19, 'PageFooter', '$date', '\"\"<div style=\"text-align:center\">\"\"\n(>^_^)> Galope sous [[http://www.yeswiki.net YesWiki]] <(^_^<)\n\"\"</div>\"\" \n', '', 'WikiAdmin', 'WikiAdmin', 'Y', 'page', ''),
(20, 'PageMenu', '$date', ' - \"\"<a href=\"wakka.php?wiki=\"\"{{configuration param=\"root_page\"}}\"\"\" title=\"Aller sur la page d''accueil\">Accueil</a>\"\"', '', 'WikiAdmin', 'WikiAdmin', 'Y', 'page', ''),
(21, 'NomWiki', '$date', 'Un NomWiki est un nom qui est écrit \"\"CommeCela\"\".\n\nUn NomWiki est transformé automatiquement en lien. Si la page correspondante n''existe pas, un ''?'' est affiché à côté du mot.', '', 'WikiAdmin', 'WikiAdmin', 'Y', 'page', ''),
(22, 'ActionChangeStyle', '$date', 'L''action ##\"\"{{ChangeStyle}}\"\"## affiche un lien qui permet de sélectionner un style graphique alternatif pour l''ensemble du site. Il n''est pas nécessaire d''enregistrer sa préférence dans les paramètres utilisateur, c''est l''action qui s''en charge.\n\nLes feuilles de styles alternatives remplacent la feuille //wakka.css// et peuvent donc se baser sur cette dernière. Les fichiers correspondant doivent au préalable avoir été déposé sur le serveur web, à la racine du site \"\"WikiNi\"\". Déposer un tel fichier requiert généralement un accès FTP, ce qui en fait une opération réservée aux administrateurs du site.\n\n==== Paramètres ====\nCette action accepte deux paramètres :\n - //link// (obligatoire) : précise quelle feuille de style utiliser ;\n - //title// (facultatif) : précise un texte spécifique pour le lien qui sera affiché. --- En l''absence de ce paramètre, le texte affiché est \"Feuille de style\", suivi du nom donné dans le paramètre //link//.\n\nPar exemple : ##\"\"{{changestyle link=\"orangelight100\" title=\"Le style OrangeLight100\"}}\"\"## affiche un lien, dont le texte sera \"Le style \"\"OrangeLight100\"\"\", et qui permettra d''utiliser la feuille de style //orangelight100.css//. Le fichier //orangelight100.css// devra avoir été déposé à la racine du site \"\"WikiNi\"\" au préalable.\n\n----\n{{trail toc=\"ListeDesActionsWikini\"}}', '', 'WikiAdmin', 'WikiAdmin', 'Y', 'page', ''),
(23, 'ActionListPages', '$date', 'L''action ##\"\"{{ListPages}}\"\"## liste la totalité des pages du site.\nPour obtenir la liste des pages du site on pourra voir également l''action [[ActionPageIndex PageIndex]].\n\nL''action ##\"\"ListPages\"\"## s''utilise avec différents paramètres :\n\n  - ##\"\"{{ListPages}}\"\"## : établi un IndexDesPages, liste de toutes les pages du site dans l''ordre alphabétique de leur nom, avec leur propriétaire (identique à ##\"\"{{ListPages/sort}}\"\"## et ##\"\"{{ListPages/sort=\"tag\"}}\"\"##)\n  - ##\"\"{{ListPages/tree}}\"\"## : établi un PlanDuSite, c''est-à-dire une liste hiérarchique des pages sur trois niveaux à partir de la page d''accueil (cette action ne liste donc pas toutes les pages du site)\n  - ##\"\"{{ListPages/tree=\"MotWiki\"}}\"\"## : établi une liste hiérarchique des pages sur trois niveaux à partir de la page passée en paramètre, ici \"\"MotWiki\"\".\n  - ##\"\"{{ListPages/sort}}\"\"## : liste de toutes les pages du site classées par ordre alphabétique (identique à ##\"\"{{ListPages}}\"\"## et ##\"\"{{ListPages/sort=\"tag\"}}\"\"##)\n  - ##\"\"{{ListPages/sort=\"time\"}}\"\"## : liste toutes les pages du site classées par ordre de dernière date de modification\n  - ##\"\"{{ListPages/sort=\"owner\"}}\"\"## : liste de toute les pages du site classées par ordre du nom du propriétaire de la page\n  - ##\"\"{{ListPages/sort=\"user\"}}\"\"## : liste de toutes les pages du site classées par ordre du nom du dernier utilisateur à l''avoir modifiée\n  - ##\"\"{{ListPages/sort=\"tag\"}}\"\"## : liste de toutes les pages du site classées par ordre alphabétique (identique à ##\"\"{{ListPages}}\"\"## et ##\"\"{{ListPages/sort}}\"\"##)\n\n----\n{{trail toc=\"ListeDesActionsWikini\"}}\n', '', 'WikiAdmin', 'WikiAdmin', 'Y', 'page', ''),
(24, 'ControlerLAccesAuxPages', '$date', 'Chaque page possède trois niveaux de contrôle d''accès :\n - lecture de la page\n - écriture/modification de la page\n - commentaire de la page\n\nLes contrôles d''accès ne peuvent être modifiés que par le propriétaire de la page -- l''administrateur technique peut aussi manuellement modifier ces contrôles en travaillant directement sur la base de données.\nLe propriétaire d''une page voit apparaître, dans la page dont il est propriétaire, l''option \"Éditer permissions\" : cette option lui permet de modifier les contrôles d''accès.\nCes contrôles sont matérialisés par des colonnes où le propriétaire va ajouter ou supprimer des informations.\nLe propriétaire peut compléter ces colonnes par les informations suivantes, séparées par des espaces :\n - le nom d''un ou plusieurs utilisateurs : par exemple \"\"CharlesNepote\"\" ou \"\"DavidDelon\"\"\n - le caractère ***** désignant tous les utilisateurs\n - le caractère **+** désignant les utilisateurs enregistrés\n - le caractère **!** signifiant la négation : par exemple !\"\"CharlesNepote\"\" signifie que \"\"CharlesNepote\"\" **ne doit pas** avoir accès à cette page\n\n===== Droits d''accès par défaut =====\nPour toute nouvelle page créée, [[http://www.wikini.net WikiNi]] applique des droits d''accès par défaut. Ces droits d''accès sont configurables via le fichier /wakka.config.php.\nIl faut renseigner les trois variables de configuration suivantes :\n##\n	\"default_write_acl\" => \"*\",\n	\"default_read_acl\" => \"*\",\n	\"default_comment_acl\" => \"*\",\n##\n\nPar exemple, vous pouvez souhaiter que, par défaut, seuls les utilisateurs enregistrés puisse modifier des pages. Vous utiliserez alors :\n##\n	\"default_write_acl\" => \"+\",\n	\"default_read_acl\" => \"*\",\n	\"default_comment_acl\" => \"*\",\n##\n', '', 'WikiAdmin', 'WikiAdmin', 'Y', 'page', ''),
(25, 'PageColonneDroite', '$date', 'En éditant la PageColonneDroite, on peut modifier cette zone.', '', 'WikiAdmin', 'WikiAdmin', 'Y', 'page', ''),
(26, 'PageMenuHaut', '$date', ' - \"\"<a href=\"wakka.php?wiki=\"\"{{configuration param=\"root_page\"}}\"\"\" title=\"Aller sur la page d''accueil\">Accueil</a>\"\"', '', 'WikiAdmin', 'WikiAdmin', 'Y', 'page', ''),
(27, 'AideWikiNi', '$date', '=====Les pages d''aide sur [[http://www.wikini.net WikiNi]]=====\n\n	- ReglesDeFormatage : résumé des syntaxes \"\"WikNi\"\" permettant la mise en forme du texte.\n	- ListeDesActionsWikini : liste des actions disponible dans [[http://www.wikini.net WikiNi]].\n	- ControlerLAccesAuxPages : explique comment gérer les droits d''accès aux page de [[http://www.wikini.net WikiNi]].', '', 'WikiAdmin', 'WikiAdmin', 'Y', 'page', ''),
(28, 'BacASable', '$date', 'Faites vos test sur [[http://www.wikini.net WikiNi]] sur cette page\n', '', 'WikiAdmin', 'WikiAdmin', 'Y', 'page', ''),
(29, 'DerniersChangements', '$date', '{{RecentChanges}}', '', 'WikiAdmin', 'WikiAdmin', 'Y', 'page', ''),
(30, 'TableauDeBordDeCeWiki', '$date', 'Ce tableau de bord regroupe toutes les pages utiles à l''analyse et à l''animation de ce site.\n  - DerniersChangements et DerniersCommentaires\n  - PlanDuSite à partir de la racine\n  - IndexDesPages, IndexDesPagesBis \n  - PagesOrphelines\n  - PagesACreer\n  - ParametresUtilisateur\n\n----\n==== 8 derniers comptes utilisateurs ====\n{{Listusers last=\"8\"}}\n==== 8 dernières pages modifiées ====\n{{recentchanges max=\"8\"}}\n==== 5 dernières pages commentées ====\n{{RecentlyCommented max=\"5\"}}\n', '', 'WikiAdmin', 'WikiAdmin', 'Y', 'page', ''),
(31, 'ActionUserSettings', '$date', 'L''action \"\"{{UserSettings}}\"\" permet aux utilisateurs d''effectuer les actions suivantes :\n - création d''un nouveau compte\n - authentification\n - réglage des paramètres utilisateur\n - changement de mot-de-passe\n\nOn peut la voir en action dans les ParametresUtilisateur.\n\n----\n{{trail toc=\"ListeDesActionsWikini\"}}\n', '', 'WikiAdmin', 'WikiAdmin', 'Y', 'page', ''),
(32, 'PageHeader', '$date', '====== {{configuration param=\"wakka_name\"}} ======', '', 'WikiAdmin', 'WikiAdmin', 'Y', 'page', ''),
(33, 'IndexDesPages', '$date', '{{listpages}}', '', 'WikiAdmin', 'WikiAdmin', 'Y', 'page', ''),
(34, 'AidE', '$date', '=====Les pages d''aide sur [[http://www.wikini.net WikiNi]]=====\n\n	- [[CoursUtilisationYesWiki Cours sur l''utilisation de YesWiki]]\n	- ReglesDeFormatage : résumé des syntaxes \"\"WikNi\"\" permettant la mise en forme du texte.\n	- ListeDesActionsWikini : liste des actions disponible dans [[http://www.wikini.net WikiNi]].\n	- ControlerLAccesAuxPages : explique comment gérer les droits d''accès aux page de [[http://www.wikini.net WikiNi]].\n', '', 'WikiAdmin', 'WikiAdmin', 'Y', 'page', ''),
(35, 'ListeDesActionsWikini', '$date', 'Wikini propose par défaut les \"actions\" suivantes.\n\n  - ActionBacklinks : liste de toutes les pages faisant référence à la page courante\n  - ActionChangeStyle : changer le style graphique du wiki\n  - ActionEraseSpamedComments : effacer facilement les spams de commentaires\n  - ActionFindpage\n  - ActionInclude : inclusion d''une page au sein d''une autre\n  - ActionListPages\n  - ActionListUsers\n  - ActionMyChanges\n  - ActionMyPages\n  - ActionOrphanedPages : recherche les pages qui n''ont pas de liens vers elle (par orpheline )\n  - ActionPageIndex\n  - ActionRecentChanges\n  - ActionRecentChangesRSS\n  - ActionRecentComments\n  - ActionRecentlyCommented\n  - ActionRedirect : redirection d''une page vers une autre\n  - ActionTextSearch : recherche d''une chaine de caractères dans l''ensemble des page de [[http://www.wikini.net WikiNi]]\n  - ActionTrail : permet de lier des pages entres elles et de passer de l''une à l''autre avec un petit navigateur style \"précédente/suivante\"\n  - ActionUserSettings\n  - ActionWantedPages : liste les pages devant être écrites.\n\n  ', '', 'WikiAdmin', 'WikiAdmin', 'Y', 'page', ''),
(36, 'PageRapideHaut', '$date', '\"\"<a href=\"wakka.php?wiki=\"\"{{configuration param=\"root_page\"}}\"\"\" title=\"Lien pour la page d\"accueil de la ferme de wikis\">La ferme de wikis</a>\"\" [[AidE Aide]] [[TableauDeBordDeCeWiki Tableau de bord]] \"\"<img class=\"ferme\" src=\"tools/templates/themes/yeswiki/images/supagro_ferme.png\" alt=\"La ferme de Wiki de SupAgro\" />\"\"{{moteurrecherche class=\"right\"}}\"\"<a class=\"right\" href=\"wakka.php?wiki=DerniersChangementsRss/xml\" title=\"S\"abonner au flux RSS des derniers changements\"><img src=\"tools/templates/presentation/images/rss-icon12-black.png\" alt=\"rss\" /></a>\"\"', '', 'WikiAdmin', 'WikiAdmin', 'Y', 'page', ''),
(37, 'ActionEraseSpamedComments', '$date', 'L''action ##\"\"{{EraseSpamedComments}}\"\"## permet d''effacer facilement les commentaires contenant du SPAM. Cette action n''est accessible qu''aux administrateurs.\n\nL''action liste les derniers commentaires déposés sur le site, et l''administrateur peut choisir lesquels doivent être éliminés. Il lui suffit de cocher les cases correspondantes et de valider le formulaire.\n\n\n===== Paramètres =====\nCette action accepte 2 paramètres :\n - //max// (optionnel) : limite le nombre de commentaires listés. --- Valeur par défaut : 0 (pas de limite)\n - //logpage// (optionnel) : spécifie la page où sera déposé le journal des suppressions effectuées. --- Par défaut, le journal des suppressions effectuées est ajouté en fin de la page courante.\n\nLe journal est ajouté en fin de la page désignée, donc le contenu précédent de n''est pas altéré.\nLe journal est consigné même si l''administrateur n''a pas le droit d''écriture sur à la page cible.\n\nExemple d''utilisation : ##\"\"{{erasespamedcomments max=\"50\" logpage=\"HistoriqueDesSuppressionsDesSpams}}\"\"##.\n\n----\n{{trail toc=\"ListeDesActionsWikini\"}}', '', 'WikiAdmin', 'WikiAdmin', 'Y', 'page', ''),
(38, 'PremiersPasSurLeWiki', '$date', '===== Qu''est-ce qu''un wiki ? =====\nUn wiki c''est :\n - un site collaboratif où tout le monde peut écrire : créer et modifier des pages\n - un site où l''historique de chaque édition est conservé : si vous modifiez une page, la version précédente est automatiquement sauvegardée\n - un site où vous pouvez voir précisément ce qui a changé entre deux versions d''une même page\n - un site où vous pouvez facilement observer tous les changements de toutes les pages\n\nCette page vous propose d''en voir le fonctionnement en quelques minutes.\n\n===== 1. Modifier une page =====\n - Rendez-vous sur la page que vous souhaitez modifier.\n - Cliquez sur le lien en bas à gauche \"##Éditer cette page##\".\n - Un formulaire apparait avec le texte de la page : vous pouvez modifier le texte.\n - Une fois le texte modifié, cliquer sur le bouton \"##Sauver##\" en bas page : ça y est, c''est publié !\n     Vous pouvez également appuyer sur le Bouton \"Aperçu\" pour visualiser vos modifications avant publication. Sur certains wikis l''aperçu est d''ailleurs obligatoire, afin de vous inciter à relire vos modifications.\n\nLes [[ReglesDeFormatage règles de formatage]] permettent d''afficher du texte en **gras**, en //italique//, etc. Si vous souhaitez essayer tout cela, rendez-vous dans le BacASable, c''est un endroit fait pour ça.\n\n===== 2. Créer une page =====\nUne page orpheline n''a pas de sens sur un wiki. La façon la plus efficace de créer une page est donc d''abord de créer le lien qui conduit à cette page.\nPour cela il suffit d''employer un **MotWiki**, pour créer automatiquement un lien vers une page du même nom. Un MotWiki représente deux mots collés ensemble, chacun débutant par une majuscule : par exemple ##\"\"CommeCeci\"\"## ou ##\"\"CommeCela\"\"##.\nL''utilisation d''un MotWiki ne correspondant à aucune page crée à l''enregistrement un \"?\" au côté de votre mot : en cliquant dessus, vous entrerez dans votre nouvelle page ayant comme nom le MotWiki.\nPour aller plus loin, il existe d''autres méthodes pour créer des liens, décrites dans les ReglesDeFormatage.\n\n==== Choisir un nom de page efficace ====\nLe nom des pages est un facteur important de la lisibilité d''un wiki.\nQuelques règles simples peuvent aider le rédacteur à choisir un nom efficace :\n - le nom ne possède pas d''article ; ##\"\"UneTarteTatin\"\"## complique l''utilisation de ce nom alors que ##\"\"TarteTatin\"\"## la simplifie : exemple : //Il faut servir la ##\"\"TarteTatin\"\"##// est difficile à exprimer avec ##\"\"UneTarteTatin\"\"##.\n - le nom peut être plus court et général lorsqu''il se rapporte au sujet principal du wiki ; à l''inverse il doit se spécialiser à mesure qu''il s''éloigne de ce sujet.\n - pour une meilleure lisibilité, respecter la majuscule au début de chaque mot d''un mot wiki : préférer ##\"\"TenueDeSoiree\"\"## à ##\"\"TenuedeSoiree\"\"##.\n\n===== 3. Suivre la vie du site =====\nLa page DerniersChangements permet de visualiser les modifications effectués sur les pages du site, par ordre antéchronologique.\n\n===== 4. Afficher les dernières modifications d''une page =====\nPour visualiser l''historique des modifications d''une page cliquer sur la date de dernière modification, au bas de la page : \nPar exemple : http://www.wikini.net/wakka.php?wiki=PagePrincipale/revisions\nSélectionner alors les deux versions que vous désirez comparer et cliquer sur le bouton \"##Voir les différences##\".\nLa page se réaffiche alors avec les modifications surlignées en rouge.\n\n===== 5. Récupérer une ancienne version d''une page =====\nIl peut arriver d''avoir besoin de récupérer une ancienne version d''une page donnée -- typiquement parce que vous avez supprimé le texte par mégarde ou bien en cas de vandalisme.\nPour cela :\n - il vous faut d''abord visualiser l''historique des modifications d''une page en cliquant sur la date de dernière modification, au bas de la page : par exemple : http://www.wikini.net/wakka.php?wiki=PagePrincipale/revisions\n - ensuite vous devez sélectionner la page à récupérer en cliquant sur le lien correspondant dans la page des \"##revisions##\"\n - au bas de la page sélectionnée doit alors s''afficher un bouton qui vous permettra de \"##Rééditer cette version archivée##\" et donc de récupérer cette page\n\n===== 6. Supprimer une page =====\nPour supprimer une page :\n - il faut être propriétaire de la page ; si ce n''est pas le cas, demander au propriétaire de la supprimer pour vous\n - il faut supprimer tous les liens existant qui pointent vers cette page : ceci permet d''éviter d''avoir des liens brisés sur le site, ces derniers étant donc impossibles sur le site ; pour connaitre les liens pointant vers la page à supprimer il suffit de cliquer sur le titre de cette page en haut à droite (fonction de rétroliens)\n - cliquer enfin sur le lien \"##Supprimer##\" en bas de page\n ', '', 'WikiAdmin', 'WikiAdmin', 'Y', 'page', ''),
(39, 'ActionPageIndex', '$date', 'L''action ##\"\"{{PageIndex}}\"\"## liste toutes les pages classées par ordre alphabétique et regroupées par lettre. On peut la voir en action sur l''IndexDesPagesBis.\nPour obtenir la liste des pages du site on pourra voir également l''action [[ActionListPages ListPages]].\n\nCette action ne prend aucun paramètre.\n\n----\n{{trail toc=\"ListeDesActionsWikini\"}}\n', '', 'WikiAdmin', 'WikiAdmin', 'Y', 'page', ''),
(40, 'ParametresUtilisateur', '$date', '{{UserSettings}}', '', 'WikiAdmin', 'WikiAdmin', 'Y', 'page', ''),
(41, 'CoursUtilisationYesWiki', '$date', '======Cours sur l''utilisation de YesWiki======\n====Le principe \"Wiki\"====\nWiki Wiki signifie rapide, en Hawaïen. \n==N''importe qui peut modifier la page==\n[[http://the.honoluluadvertiser.com/dailypix/2002/Aug/19/ln07a_b.jpg le bus wiki wiki]]\n\n**Les Wiki sont des dispositifs permettant la modification de pages Web de façon simple, rapide et interactive.**\nYesWiki fait partie de la famille des wiki. Il a la particularité d''être très facile à installer.\n\n=====Mettre du contenu=====\n====Écrire ou coller du texte====\n - Dans chaque page du site, un double clic sur la page ou un clic sur le lien \"Éditer cette page\" en bas de page permet de passer en mode \"Édition\".\n - On peut alors écrire ou coller du texte\n - On peut voir un aperçu des modifications ou sauver directement la page modifiée en cliquant sur les boutons en bas de page.\n\n====Écrire un commentaire (optionnel)====\nSi la configuration de la page permet d''ajouter des commentaires, on peut cliquer sur : Afficher commentaires/formulaire en bas de chaque page.\nUn formulaire apparaitra et vous permettra de rajouter votre commentaire.\n\n\n=====Mise en forme : Titres et traits=====\n--> Voir la page ReglesDeFormatage\n\n====Faire un titre====\n======Très gros titre====== \ns''écrit en syntaxe wiki : \"\"======Très gros titre======\"\"\n\n\n==Petit titre== \ns''écrit en syntaxe wiki : \"\"==Petit titre==\"\" \n\n\n//On peut mettre entre 2 et 6 = de chaque coté du titre pour qu''il soit plus petit ou plus grand//\n\n====Faire un trait de séparation====\nPour faire apparaitre un trait de séparation\n----\ns''écrit en syntaxe wiki : \"\"----\"\"\n\n=====Mise en forme : formatage texte=====\n====Mettre le texte en gras====\n**texte en gras**\ns''écrit en syntaxe wiki : \"\"**texte en gras**\"\" \n\n====Mettre le texte en italique====\n//texte en italique//\ns''écrit en syntaxe wiki : \"\"//texte en italique//\"\"\n\n====Mettre le texte en souligné====\n__texte en souligné__\ns''écrit en syntaxe wiki : \"\"__texte en souligné__\"\"\n\n=====Mise en forme : listes=====\n====Faire une liste à puce====\n - point 1\n - point 2\n\ns''écrit en syntaxe wiki : \n\"\" - point 1\"\"\n\"\" - point 2\"\"\n\nAttention : de bien mettre un espace devant le tiret pour que l''élément soit reconnu comme liste\n\n\n====Faire une liste numérotée====\n 1) point 1\n 2) point 2\n\ns''écrit en syntaxe wiki : \n\"\" 1) point 1\"\"\n\"\" 2) point 2\"\"\n\n=====Les liens : le concept des \"\"ChatMots\"\"=====\n====Créer une page YesWiki : ====\nLa caractéristique qui permet de reconnaitre un lien dans un wiki : son nom avec un mot contenant au moins deux majuscules non consécutives (un \"\"ChatMot\"\", un mot avec deux bosses). \n\n==== Lien interne====\n - On écrit le \"\"ChatMot\"\" de la page YesWiki vers laquelle on veut pointer.\n  - Si la page existe, un lien est automatiquement créé\n  - Si la page n''existe pas, apparait un lien avec crayon. En cliquant dessus on arrive vers la nouvelle page en mode \"Édition\".\n\n=====Les liens : personnaliser le texte=====\n====Personnaliser le texte du lien internet====\nentre double crochets : \"\"[[AccueiL aller à la page d''accueil]]\"\", apparaitra ainsi : [[AccueiL aller à la page d''accueil]].\n\n====Liens vers d''autres sites Internet====\nentre double crochets : \"\"[[http://outils-reseaux.org aller sur le site d''Outils-Réseaux]]\"\", apparaitra ainsi : [[http://outils-reseaux.org aller sur le site d''Outils-Réseaux]].\n\n\n=====Télécharger une image, un document=====\n====On dispose d''un lien vers l''image ou le fichier====\nentre double crochets :\n - \"\"[[http://mondomaine.ext/image.jpg texte de remplacement de l''image]]\"\" pour les images.\n - \"\"[[http://mondomaine.ext/document.pdf texte du lien vers le téléchargement]]\"\" pour les documents.\n\n====L''action \"attach\"====\nEn cliquant sur le pictogramme représentant une image dans la barre d''édition, on voit apparaître la ligne de code suivante :\n\"\"{{attach file=\" \" desc=\" \" class=\"left\" }} \"\"\n\nEntre les premières guillemets, on indique le nom du document (ne pas oublier son extension (.jpg, .pdf, .zip).\nEntre les secondes, on donne quelques éléments de description qui deviendront le texte du lien vers le document\nLes troisièmes guillemets, permettent, pour les images, de positionner l''image à gauche (left), ou à droite (right) ou au centre (center)\n\"\"{{attach file=\"nom-document.doc\" desc=\"mon document\" class=\"left\" }} \"\"\n\nQuand on sauve la page, un lien en point d''interrogation apparait. En cliquant dessus, on arrive sur une page avec un système pour aller chercher le document sur sa machine (bouton \"parcourir\"), le sélectionner et le télécharger.\n\n=====Intégrer du html=====\nSi on veut faire une mise en page plus compliquée, ou intégrer un widget, il faut écrire en html. Pour cela, il faut mettre notre code html entre double guillemets.\nPar exemple : \"\"<textarea style=\"width:100%;\">&quot;&quot;<span style=\"color:#0000EE;\">texte coloré</span>&quot;&quot;</textarea>\"\"\ndonnera :\n\"\"<span style=\"color:#0000EE;\">texte coloré</span>\"\"\n\n\n=====Les pages spéciales=====\n - PageHeader\n - PageFooter\n - PageMenuHaut\n - PageMenu\n - PageRapideHaut\n\n - PagesOrphelines\n - TableauDeBordDeCeWiki\n \n\n=====Les actions disponibles=====\nVoir la page spéciale : ListeDesActionsWikini\n\n**les actions à ajouter dans la barre d''adresse:**\nrajouter dans la barre d''adresse :\n/edit : pour passer en mode Edition\n/slide_show : pour transformer la texte en diaporama\n\n===La barre du bas de page permet d''effectuer diverses action sur la page===\n - voir l''historique\n - partager sur les réseaux sociaux\n...\n\n=====Suivre la vie du site=====\n - Dans chaque page, en cliquant sur la date en bas de page on accède à **l''historique** et on peut comparer les différentes versions de la page.\n\n - **Le TableauDeBordDeCeWiki : ** pointe vers toutes les pages utiles à l''analyse et à l''animation du site.\n\n - **La page DerniersChangements** permet de visualiser les modifications qui ont été apportées sur l''ensemble du site, et voir les versions antérieures. Pour l''avoir en flux RSS DerniersChangementsRSS\n\n - **Les lecteurs de flux RSS** :  offrent une façon simple, de produire et lire, de façon standardisée (via des fichiers XML), des fils d''actualité sur internet. On récupère les dernières informations publiées. On peut ainsi s''abonner à différents fils pour mener une veille technologique par exemple.\n[[http://www.wikini.net/wakka.php?wiki=LecteursDeFilsRSS Différents lecteurs de flux RSS]]\n\n\n\n=====L''identification=====\n====Première identification = création d''un compte YesWiki====\n    - aller sur la page spéciale ParametresUtilisateur, \n    - choisir un nom YesWiki qui comprend 2 majuscules. //Exemple// : JamesBond\n    - choisir un mot de passe et donner un mail\n    - cliquer sur s''inscrire\n\n====Identifications suivantes====\n    - aller sur ParametresUtilisateur, \n    - remplir le formulaire avec son nom YesWiki et son mot de passe\n    - cliquer sur \"connexion\"\n\n\n\n=====Gérer les droits d''accès aux pages=====\n - **Chaque page possède trois niveaux de contrôle d''accès :**\n     - lecture de la page\n     - écriture/modification de la page\n     - commentaire de la page\n\n - **Les contrôles d''accès ne peuvent être modifiés que par le propriétaire de la page**\nOn est propriétaire des pages que l''ont créent en étant identifié. Pour devenir \"propriétaire\" d''une page, il faut cliquer sur Appropriation. \n\n - Le propriétaire d''une page voit apparaître, dans la page dont il est propriétaire, l''option \"**Éditer permissions**\" : cette option lui permet de **modifier les contrôles d''accès**.\nCes contrôles sont matérialisés par des colonnes où le propriétaire va ajouter ou supprimer des informations.\nLe propriétaire peut compléter ces colonnes par les informations suivantes, séparées par des espaces :\n     - le nom d''un ou plusieurs utilisateurs : par exemple \"\"JamesBond\"\" \n     - le caractère ***** désignant tous les utilisateurs\n     - le caractère **+** désignant les utilisateurs enregistrés\n     - le caractère **!** signifiant la négation : par exemple !\"\"JamesBond\"\" signifie que \"\"JamesBond\"\" **ne doit pas** avoir accès à cette page\n\n - **Droits d''accès par défaut** : pour toute nouvelle page créée, YesWiki applique des droits d''accès par défaut : sur ce YesWiki, les droits en lecture et écriture sont ouverts à tout internaute.\n\n=====Supprimer une page=====\n\n - **2 conditions :**\n    - **on doit être propriétaire** de la page et **identifié** (voir plus haut),\n    - **la page doit être \"orpheline\"**, c''est-à-dire qu''aucune page ne pointe vers elle (pas de lien vers cette page sur le YesWiki), on peut voir toutes les pages orphelines en visitant la page : PagesOrphelines\n\n - **On peut alors cliquer sur l''''option \"Supprimer\"** en bas de page.\n\n\n\n=====Changer le look et la disposition=====\nEn mode édition, si on est propriétaire de la page, ou que les droits sont ouverts, on peut changer la structure et la présentation du site, en jouant avec les listes déroulantes en bas de page : Thème, Squelette, Style.\n\n', '', 'WikiAdmin', 'WikiAdmin', 'Y', 'page', ''),
(42, 'IndexDesPagesBis', '$date', '{{pageindex}}', '', 'WikiAdmin', 'WikiAdmin', 'Y', 'page', ''),
(43, 'ActionTrail', '$date', 'L''action ##\"\"{{trail toc=\"NomDePage\"}}\"\"## permet de lier des pages entres elles grace à une page de sommaire. Cette action affiche un navigateur du type \"précedente/suivante\" en indiquant le nom des pages précende et suivante.\n\n====Paramètre====\nLe paramètre ##toc## permet d''indiquer le nom de la page contenant le liste des pages liées.\n\n====Configuration====\nL''aspet des liens du navigateur est définis par deux classe CSS présente dans wakka.css :\n##\n.trail_table { line-height: 30px;}\n.trail_button { color: #993333; }\n##\n\n====Ecriture d''une page \"toc\"====\nCette page peut contenir n''importe quel texte. Les règles qui permettent de définir la liste des pages liées sont :\n  - Le nom de la page appartient à une liste (numéroté, à bulle ou sans signe)\n  - Le nom de la page est le **1er** mot de chaque élément de la liste\n  - Les liens ##\"\"[[NomPageWikiNi Nom d''une page WikiNi]]\"\"## sont acceptés et doivent être le **1er mot** de chaque éléments de la liste.\n\nUn exemple de page sommaire :\n-----\n\n====Sommaire====\n\nTexte texte texte texte texte texte texte texte texte texte texte texte texte texte texte texte texte texte texte texte texte texte texte texte texte texte texte texte texte.\n\n	- Page1 : texte texte texte texte texte texte texte texte texte texte texte \n	- Page2 : texte texte texte texte texte texte texte texte texte texte texte texte texte \n	- [[Page3 Vers la page 3]] : texte texte texte texte texte texte texte texte texte texte texte texte texte texte texte texte texte texte texte texte \n		- Page31 : texte texte texte texte texte texte texte texte texte texte texte \n		- Page32 : texte texte texte texte texte texte texte texte texte texte texte \n	- Page4 : texte texte texte texte texte texte texte texte texte texte texte \n\ntexte texte texte texte texte texte texte texte texte texte texte texte texte texte texte texte texte texte texte texte texte texte texte texte texte texte texte texte texte texte.\n	\n	- Page5 : texte texte texte texte texte texte texte texte texte texte texte texte texte texte texte texte texte texte \n	- Page6 : texte texte texte texte texte texte texte texte texte texte texte texte texte texte texte \n-----\n{{trail toc=\"ListeDesActionsWikiNi\"}}', '', 'WikiAdmin', 'WikiAdmin', 'Y', 'page', ''),
(44, 'ActionWantedPages', '$date', 'L''action \"\"{{WantedPages}}\"\" liste tous les MotWiki du site qui n''ont pas vu la création d''une page.\nCette page est visible en action sur les PagesACreer.\n\n----\n{{trail toc=\"ListeDesActionsWikini\"}}\n', '', 'WikiAdmin', 'WikiAdmin', 'Y', 'page', '');",

"CREATE TABLE IF NOT EXISTS `".$table_prefix."referrers` (
  `page_tag` char(50) NOT NULL DEFAULT '',
  `referrer` char(150) NOT NULL DEFAULT '',
  `time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  KEY `idx_page_tag` (`page_tag`),
  KEY `idx_time` (`time`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;",

"INSERT INTO `".$table_prefix."referrers` (`page_tag`, `referrer`, `time`) VALUES
('Accueil', 'http://webtest.cdrflorac.fr/ferme/wikiTest/wakka.php?installAction=writeconfig', '2012-03-22 15:17:21');",

"CREATE TABLE IF NOT EXISTS `".$table_prefix."triples` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `resource` varchar(255) NOT NULL DEFAULT '',
  `property` varchar(255) NOT NULL DEFAULT '',
  `value` text NOT NULL,
  PRIMARY KEY (`id`),
  KEY `resource` (`resource`),
  KEY `property` (`property`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=2 ;",

"INSERT INTO `".$table_prefix."triples` (`id`, `resource`, `property`, `value`) VALUES
(1, 'ThisWikiGroup:admins', 'http://www.wikini.net/_vocabulary/acls', 'WikiAdmin');",

"CREATE TABLE IF NOT EXISTS `".$table_prefix."users` (
  `name` varchar(80) NOT NULL DEFAULT '',
  `password` varchar(32) NOT NULL DEFAULT '',
  `email` varchar(50) NOT NULL DEFAULT '',
  `motto` text NOT NULL,
  `revisioncount` int(10) unsigned NOT NULL DEFAULT '20',
  `changescount` int(10) unsigned NOT NULL DEFAULT '50',
  `doubleclickedit` enum('Y','N') NOT NULL DEFAULT 'Y',
  `signuptime` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `show_comments` enum('Y','N') NOT NULL DEFAULT 'N',
  PRIMARY KEY (`name`),
  KEY `idx_name` (`name`),
  KEY `idx_signuptime` (`signuptime`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;",

"INSERT INTO `".$table_prefix."users` (`name`, `password`, `email`, `motto`, `revisioncount`, `changescount`, `doubleclickedit`, `signuptime`, `show_comments`) VALUES
('WikiAdmin', 'c23cc813361e0f1d723c4062217e08a9', 'florestan.bredow@supagro.inra.fr', '', 20, 50, 'Y', '$date', 'N');",
);/**/
?>
