parameters:
  contact_mail_func: 'mail'       # mail, sendmail ou smtp
  contact_smtp_host: ''           # serveur smtp hote
  contact_smtp_port: ''           # port smtp utilisé
  contact_smtp_user: ''           # utilisateur smtp
  contact_smtp_pass: ''           # mot de passe smtp
  mail_template: 'email.tpl.html' # template de base pour les mails html
  contact_reply_to: ''            # default mail to reply to
  contact_debug: 0                # debug mode (0 pour rien, 1 pour normal, 2 pour détaillé)
  contact_passphrase: ''          # passphrase pour envoyer des mail
