on: [push, workflow_dispatch]
jobs:
  phpunit:
    runs-on: docker
    env:
      MYSQL_DATABASE: yeswiki
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: yeswiki
      MYSQL_PASSWORD: password
    container:
      image: code.yeswiki.net/sylvainlehmann/php:8-2
    services:
      yeswiki-db:
        image: mysql:8.0
    steps:
      - run:  apt update && apt install -y inetutils-ping  && ping yeswiki-db
#      - uses: actions/checkout@v4
#      - name: Cache dependencies
#        uses: actions/cache@v4
#        with:
#          path: |
#            node_modules
#            vendor
#          key: ${{ forge.job }}-${{ forge.ref_name }}
#      - run: /opt/install.sh
#      - run: ./tests/tests.sh
