on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: docker
    env:
      GITHUB_WORKSPACE: /var/www/html/
    defaults:
      run:
        working-directory: /var/www/html/
    container:
      image: code.yeswiki.net/sylvainlehmann/php:8-2
    steps:
      - uses: actions/checkout@v4
#      - run: composer install
      - run: ls -al
