on: [push, workflow_dispatch]
jobs:
  phpunit:
    runs-on: docker
    container:
      image: code.yeswiki.net/sylvainlehmann/php:8-2
    services:
      yeswiki-db:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: yeswiki
          MYSQL_USER: yeswiki
          MYSQL_PASSWORD: secret
    steps:
      - uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            vendor
          key: ${{ forge.job }}-${{ forge.ref_name }}
      - run: /opt/install.sh
      - run: /opt/entrypoint_test.php &
      - run: ./tests/tests.sh
