parameters:
  hello_world:
    my_param: 'this is a test param defined in tools/helloworld/config.yaml. It can be ovewritten in wakka.config.php'

services:
  _defaults:
    autowire: true
    public: true

  YesWiki\HelloWorld\Service\:
    resource: 'services/*'

  # Allows to use controllers as services
  YesWiki\HelloWorld\Controller\:
    resource: 'controllers/*'
