<?php

namespace YesWiki\Render\Service;

use YesWiki\Content\Service\LinkTracker;
use YesWiki\Kernel\Service\Performer;

/**
 * Executes an "action" module from its page syntax — the string between `{{` and `}}`
 * (historic Wiki::Action()): parses the attribute string, pauses link tracking while the
 * action runs, keeps a log of every action executed, and hands off to Performer.
 *
 * Lives in Render, not Kernel: its callers are the content formatter and the Twig
 * `action()` helper, and pausing LinkTracker is a content-rendering concern the Kernel
 * dispatcher must not know about (Kernel depends on no feature module).
 */
class ActionRunner
{
    protected Performer $performer;
    protected LinkTracker $linkTracker;

    /** @var list<array{action: string, vars: array<mixed>}> every action run so far (see actionsLog()) */
    protected $actionsLog = [];

    public function __construct(Performer $performer, LinkTracker $linkTracker)
    {
        $this->performer = $performer;
        $this->linkTracker = $linkTracker;
    }

    /**
     * @param string       $action            the name of the action and its eventual parameters,
     *                                        as it appears in the page between "{{" and "}}"
     * @param bool         $forceLinkTracking by default, link tracking is paused while the action
     *                                        runs; pass true to keep it on
     * @param array<mixed> $vars              additional parameters, as 'param' => 'value' — more
     *                                        efficient than encoding them into $action
     *
     * @return string the output generated by the action
     */
    public function action($action, $forceLinkTracking = false, array $vars = []): string
    {
        $cmd = trim($action);
        $cmd = str_replace("\n", ' ', $cmd);
        // extract $action and $vars_temp ("raw" attributes)
        if (!preg_match("/^([a-zA-Z0-9_-]+)\/?(.*)$/", $cmd, $matches)) {
            return '<div class="alert alert-danger">' . _t('INVALID_ACTION') . ' &quot;' . htmlspecialchars($cmd, ENT_COMPAT, YW_CHARSET) . '&quot;</div>' . "\n";
        }
        list(, $action, $vars_temp) = $matches;

        // match all attributes (key and value)
        if (preg_match_all('/([a-zA-Z0-9_]*)="(.*)"/U', $vars_temp, $matches)) {
            for ($a = 0; $a < count($matches[1]); $a++) {
                $vars[$matches[1][$a]] = $matches[2][$a];
            }
        }

        if (!$forceLinkTracking) {
            $this->linkTracker->stop();
        }
        // keep track of actions and their parameters
        $this->actionsLog[] = [
            'action' => $action,
            'vars' => $vars,
        ];
        $result = $this->performer->run($action, 'action', $vars);
        $this->linkTracker->start(); // shouldn't we restore the previous status ?

        return $result;
    }

    /**
     * Every action executed so far this request, with its parameters, in execution order.
     *
     * @return list<array{action: string, vars: array<mixed>}>
     */
    public function actionsLog(): array
    {
        return $this->actionsLog;
    }
}
