<?php

namespace YesWiki\Render\Service;

use YesWiki\Kernel\Service\Performer;

/**
 * Executes an "action" module from its page syntax — the string between `{{` and `}}` (historic Wiki::Action()): parses the attribute string, keeps a log of every action executed, and hands off to Performer.
 */
class ActionRunner
{
    protected Performer $performer;

    /**
     * @var list<array{action: string, vars: array<mixed>}> every action run so far (see actionsLog())
     */
    protected $actionsLog = [];

    public function __construct(Performer $performer)
    {
        $this->performer = $performer;
    }

    /**
     * @param string       $action the name of the action and its eventual parameters,
     *                             as it appears in the page between "{{" and "}}"
     * @param array<mixed> $vars   additional parameters, as 'param' => 'value' — more
     *                             efficient than encoding them into $action
     *
     * @return string the output generated by the action
     */
    public function action($action, array $vars = []): string
    {
        $cmd = trim($action);
        $cmd = str_replace("\n", ' ', $cmd);

        if (!preg_match("/^([a-zA-Z0-9_-]+)\/?(.*)$/", $cmd, $matches)) {
            return '<div class="alert alert-danger">' . _t('INVALID_ACTION') . ' &quot;' . htmlspecialchars($cmd, ENT_COMPAT, YW_CHARSET) . '&quot;</div>' . "\n";
        }
        list(, $action, $vars_temp) = $matches;

        if (preg_match_all('/([a-zA-Z0-9_]*)="(.*)"/U', $vars_temp, $matches)) {
            for ($a = 0; $a < count($matches[1]); $a++) {
                $vars[$matches[1][$a]] = $matches[2][$a];
            }
        }

        $this->actionsLog[] = [
            'action' => $action,
            'vars' => $vars,
        ];

        return $this->performer->run($action, 'action', $vars);
    }

    /**
     * Every action executed so far this request, with its parameters, in execution order.
     *
     * @return list<array{action: string, vars: array<mixed>}>
     */
    public function actionsLog(): array
    {
        return $this->actionsLog;
    }
}
