#!/usr/bin/env php
<?php
// application.php

namespace YesWiki\AutoUpdate\Commands;

if (!file_exists('wakka.config.php')) {
    exit("\e[31mThe command should be launched from your YesWiki root directory\e[0m");
} else {
    // backward compatibility for extension ferme
    // TODO delete this file
    include 'includes/commands/console';
}
