<?php

namespace YesWiki\Search\Service;

use Psr\Container\ContainerInterface;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use YesWiki\Kernel\Entity\Event;
use YesWiki\Kernel\Service\ConsoleService;

/**
 * Keeps the search index in step with the wiki (ticket 18 / ADR-0015).
 *
 * ## Everything is queued, nothing is indexed inline
 *
 * The obvious implementation -- index the Content right here, in the event handler -- was
 * written first and is wrong, for a reason worth recording because it will look like a
 * missing optimisation to the next reader.
 *
 * Indexing a Content means resolving the form that describes it, and these events fire from
 * *inside* the services that write Content. `FormManager::create()` saves the form's page
 * row before writing its type triple, so a listener that resolves forms at that moment sees
 * a row that is not a form yet, calls `FormManager::getAll()`, and leaves the form registry
 * cached **without the form being created** for the rest of the request. That surfaced as an
 * unrelated test failing three files away, which is exactly how expensive this class of bug
 * is to find.
 *
 * So the handlers only ever write to the queue -- no form resolution, no reentrancy into the
 * service that is mid-write -- and the queue is drained once the request is over. Nothing
 * user-visible is lost: the response has already been generated by then, and a visitor can
 * only search on a later request.
 *
 * ## Two speeds
 *
 * - **One Content changed** -- queued, and drained at the end of this request.
 * - **A form changed** -- its template decides which fields exist, what each contributes and
 *   which Field ACL guards it, so every entry under it is stale. Unbounded, so it is queued
 *   and a `search:reindex` is spawned to work through it out of band.
 *
 * Note what is deliberately *absent*: an ACL or metadata change needs no handler of its own.
 * Both create a `pages` revision, so `page.updated` already fires -- the very invariant that
 * lets the index denormalise `page_read_acl`, pinned by SearchIndexAclTest.
 */
class SearchIndexSubscriber implements EventSubscriberInterface
{
    /** Contents reindexed at the end of a request before the rest is left to the queue. */
    private const FLUSH_LIMIT = 200;

    /** Seconds the end-of-request flush may take before it leaves the rest queued. */
    private const FLUSH_BUDGET_SEC = 5;

    private ContainerInterface $container;
    private bool $flushRegistered = false;

    public function __construct(ContainerInterface $container)
    {
        $this->container = $container;
    }

    public static function getSubscribedEvents(): array
    {
        return [
            'page.created' => ['onContentChanged'],
            'page.updated' => ['onContentChanged'],
            'page.deleted' => ['onContentDeleted'],
            'entry.created' => ['onContentChanged'],
            'entry.updated' => ['onContentChanged'],
            'entry.deleted' => ['onContentDeleted'],
            'comment.created' => ['onContentChanged'],
            'comment.updated' => ['onContentChanged'],
            'comment.deleted' => ['onContentDeleted'],
            'form.updated' => ['onFormChanged'],
            'form.deleted' => ['onFormChanged'],
        ];
    }

    public function onContentChanged(Event $event): void
    {
        $tag = $this->tagOf($event);
        if ($tag === '') {
            return;
        }

        $this->indexer()->enqueue([$tag]);
        $this->flushWhenTheRequestIsOver();
    }

    /**
     * Deleting is safe to do inline: it is one `DELETE ... WHERE tag = ?` and resolves no
     * form, so none of the reentrancy above applies -- and a deleted Content lingering in
     * results is worse than a new one arriving a moment late.
     */
    public function onContentDeleted(Event $event): void
    {
        $tag = $this->tagOf($event);
        if ($tag !== '') {
            $this->indexer()->delete($tag);
        }
    }

    /**
     * Queue the form's entries, then try to drain them out of band.
     *
     * The queue is written first and unconditionally. The spawn is an accelerator, not the
     * mechanism: `proc_open` is disabled on a lot of shared hosting and PhpExecutableFinder
     * can hand back the FPM binary, so the failure has to be survivable -- and it is,
     * because the maintenance hook drains the very same rows.
     */
    public function onFormChanged(Event $event): void
    {
        $formId = (string)($event->getData()['id'] ?? '');
        if ($formId === '') {
            return;
        }

        if ($this->indexer()->enqueueForm($formId) > 0) {
            $this->spawnReindex();
        }
    }

    /**
     * Drain what this request queued, once it is finished writing.
     *
     * A shutdown function rather than a kernel.terminate listener because the CLI, the
     * installer and the legacy bootstrap all reach this code without a kernel around them,
     * and an index that only updates over HTTP would be a subtle way to be wrong.
     */
    private function flushWhenTheRequestIsOver(): void
    {
        if ($this->flushRegistered) {
            return;
        }
        $this->flushRegistered = true;

        $container = $this->container;
        register_shutdown_function(static function () use ($container): void {
            try {
                $container->get(SearchIndexer::class)->drain(self::FLUSH_LIMIT, self::FLUSH_BUDGET_SEC);
            } catch (\Throwable $failed) {
                // the response is already sent; whatever is left stays queued for the
                // maintenance hook rather than becoming a fatal after the fact
            }
        });
    }

    private function spawnReindex(): void
    {
        try {
            $this->container->get(ConsoleService::class)->startConsoleAsync('search:reindex', ['--drain']);
        } catch (\Throwable $unavailable) {
            // no console, no PHP binary, proc_open disabled: the queue still holds the work
            // and the maintenance hook will take it. Swallowed rather than surfaced because
            // this runs inside a webmaster's form save, which succeeded.
        }
    }

    private function tagOf(Event $event): string
    {
        $data = $event->getData();

        return (string)($data['id'] ?? $data['data']['tag'] ?? '');
    }

    private function indexer(): SearchIndexer
    {
        return $this->container->get(SearchIndexer::class);
    }
}
