<?php

namespace YesWiki\Test\Content;

use PHPUnit\Framework\Attributes\Depends;
use Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface;
use YesWiki\Import\Service\SyncScheduler;
use YesWiki\Test\Core\ForcedParameterBag;
use YesWiki\Test\Core\YesWikiTestCase;
use YesWiki\YesWikiRuntime;

require_once 'tests/YesWikiTestCase.php';
require_once 'tests/ForcedParameterBag.php';

/**
 * Which data sources the wiki's housekeeping imports, and when.
 *
 * The two things worth pinning are the two that go wrong silently. A source is *claimed*
 * before it is imported, so two page views that cross the maintenance interval together do
 * not import the same source twice -- there is no lock to notice afterwards, only a doubled
 * import. And `syncIntervalInMin` has to hold a source back across maintenance runs, or a
 * source too heavy for every half hour has no way to say so.
 */
class SyncSchedulerTest extends YesWikiTestCase
{
    private const SOURCES = [
        'every_time' => ['importer' => 'Rss', 'syncOnMaintenance' => true],
        'once_a_day' => ['importer' => 'Rss', 'syncOnMaintenance' => true, 'syncIntervalInMin' => 1440],
        'on_demand' => ['importer' => 'Rss'],
    ];

    public function testWikiExisting(): YesWikiRuntime
    {
        $wiki = $this->getWiki();
        $this->assertTrue($wiki->services->has(YesWikiRuntime::class));

        return $wiki->services->get(YesWikiRuntime::class);
    }

    #[Depends('testWikiExisting')]
    public function testOnlyFlaggedSourcesAreDue(YesWikiRuntime $wiki): void
    {
        $this->forgetPreviousRuns($wiki);
        $due = $this->scheduler($wiki)->claimDueSources();

        $this->assertSame(['every_time', 'once_a_day'], array_keys($due));
        // the options travel with the id: the importer is configured from them
        $this->assertSame('Rss', $due['every_time']['importer']);
    }

    #[Depends('testWikiExisting')]
    public function testAClaimedSourceIsNotClaimedTwice(YesWikiRuntime $wiki): void
    {
        $this->forgetPreviousRuns($wiki);
        $startedAt = time();
        $this->scheduler($wiki)->claimDueSources($startedAt);

        // a second page view crossing the same maintenance window finds nothing left to do
        $this->assertSame([], $this->scheduler($wiki)->claimDueSources($startedAt));
    }

    #[Depends('testWikiExisting')]
    public function testAPerSourceIntervalHoldsASourceBack(YesWikiRuntime $wiki): void
    {
        $this->forgetPreviousRuns($wiki);
        $scheduler = $this->scheduler($wiki);
        $scheduler->claimDueSources();

        // the next maintenance run, an hour later: the daily source is still not due, the
        // one with no interval of its own is
        $this->ageStateFile($wiki, 'every_time', 3600);
        $this->ageStateFile($wiki, 'once_a_day', 3600);

        $this->assertSame(['every_time'], array_keys($this->scheduler($wiki)->claimDueSources()));
    }

    #[Depends('testWikiExisting')]
    public function testARunIsRecordedAndReadBack(YesWikiRuntime $wiki): void
    {
        $this->forgetPreviousRuns($wiki);
        $scheduler = $this->scheduler($wiki);

        $this->assertNull($scheduler->getLastSync('every_time'), 'a source that never ran has no last sync');

        $scheduler->recordRun('every_time', "Entrée \"Fête\" mise à jour : bf_description.\n2 entrée(s) déjà à jour.");
        $last = $scheduler->getLastSync('every_time');

        $this->assertNotNull($last);
        $this->assertStringContainsString('bf_description', $last['output']);
        $this->assertLessThanOrEqual(5, abs($last['time'] - time()), 'the recorded time is when it ran');
    }

    #[Depends('testWikiExisting')]
    public function testASourceKeyCannotEscapeTheStateDirectory(YesWikiRuntime $wiki): void
    {
        // data source keys are generated by the admin page, but a hand-written config can use
        // anything as a key -- and it ends up in a file name
        $scheduler = $this->schedulerFor($wiki, ['../../evil' => ['importer' => 'Rss', 'syncOnMaintenance' => true]]);
        $scheduler->recordRun('../../evil', 'nope');

        $this->assertFileDoesNotExist('evil.log');
        $this->assertFileExists($this->stateDir($wiki) . '/.._.._evil.log');
        @unlink($this->stateDir($wiki) . '/.._.._evil.log');
    }

    private function scheduler(YesWikiRuntime $wiki): SyncScheduler
    {
        return $this->schedulerFor($wiki, self::SOURCES);
    }

    /**
     * @param array<string, array<string, mixed>> $dataSources
     */
    private function schedulerFor(YesWikiRuntime $wiki, array $dataSources): SyncScheduler
    {
        return new SyncScheduler(
            new ForcedParameterBag($wiki->services->get(ParameterBagInterface::class), ['dataSources' => $dataSources]),
            $wiki->services
        );
    }

    private function stateDir(YesWikiRuntime $wiki): string
    {
        $attachConfig = $wiki->services->get(ParameterBagInterface::class)->get('attach_config');
        $cachePath = is_array($attachConfig) ? ($attachConfig['cache_path'] ?? 'cache') : 'cache';

        return rtrim((string)$cachePath, '/') . '/importer';
    }

    private function forgetPreviousRuns(YesWikiRuntime $wiki): void
    {
        foreach (array_keys(self::SOURCES) as $id) {
            @unlink($this->stateDir($wiki) . '/' . $id . '.log');
        }
    }

    /** Pretend this source's last run happened $seconds ago. */
    private function ageStateFile(YesWikiRuntime $wiki, string $id, int $seconds): void
    {
        $file = $this->stateDir($wiki) . '/' . $id . '.log';
        if (is_file($file)) {
            touch($file, time() - $seconds);
        }
    }
}
