services:
  _defaults:
    autowire: true
    public: true

  YesWiki\Bazar\Service\FicheManager:
    arguments:
      $wiki: '%wiki%'
      $notifyAdmins: '%BAZ_ENVOI_MAIL_ADMIN%'

  YesWiki\Bazar\Service\Guard:
    arguments:
      $wiki: '%wiki%'

  bazar.fiche.manager: '@YesWiki\Bazar\Service\FicheManager'
