# Default parameters
parameters:
  BAZ_ENVOI_MAIL_ADMIN: true

services:
  bazar.fiche.manager:
    class: YesWiki\Bazar\Service\FicheManager
    arguments: ['%wiki%', '@mailer', '%BAZ_ENVOI_MAIL_ADMIN%']
    public: true
