services:
  _defaults:
    autowire: true
    public: true

  YesWiki\Core\Service\Mailer:
    arguments:
      $wiki: '%wiki%'
      $adminEmails: '%BAZ_ADRESSE_MAIL_ADMIN%'

  YesWiki\Core\Service\TripleStore:
    arguments:
      $wiki: '%wiki%'
