#!/usr/bin/env php
<?php

namespace YesWiki\Core\Commands;

use Symfony\Component\Console\Application;
use YesWiki\Core\Service\ConfigurationFileProvider;
use YesWiki\Core\Service\EnvironmentConfiguration;
use YesWiki\Core\YesWikiLoader;

// boot paths, autoloaders and private/.env before touching the config file, so a
// WAKKA_CONFIG_FILE set in the instance environment is honored by the pre-read below
// (this script lives in the source tree: <source>/includes/commands/console)
require_once dirname(__DIR__) . '/bootstrap_paths.php';
require_once dirname(__DIR__) . '/autoload.inc.php';
require_once YESWIKI_SOURCE_DIR . '/vendor/autoload.php';
require_once dirname(__DIR__) . '/YesWikiLoader.php';
YesWikiLoader::loadEnv();

$configFile = ConfigurationFileProvider::getConfigFileFromEnv();
if (!file_exists($configFile)) {
    exit("\e[31mConfiguration file not found ($configFile). The command should be launched from your YesWiki root directory\e[0m");
}

include_once $configFile;
// config files written before the rename define $wakkaConfig instead
$yeswikiConfig = (isset($yeswikiConfig) && is_array($yeswikiConfig)) ? $yeswikiConfig : ($wakkaConfig ?? []);
// environment overrides (BASE_URL, ROOT_PAGE...) apply to this pre-read like everywhere else
$yeswikiConfig = EnvironmentConfiguration::apply($yeswikiConfig);
// fake $_SERVER vars
$_SERVER['REQUEST_URI'] = $yeswikiConfig['base_url'].$yeswikiConfig['root_page'];
$_SERVER['HTTP_HOST'] = parse_url($yeswikiConfig['base_url'], PHP_URL_HOST);
$_SERVER['REQUEST_METHOD'] = 'GET';
// fake wiki page
$_REQUEST['wiki'] = $yeswikiConfig['root_page'];

$wiki = YesWikiLoader::getWiki();

// create Application
$application = new Application();

// ... register commands
foreach ([
        'core' => YESWIKI_SOURCE_DIR . '/includes/commands/*.php',
        'custom' => YESWIKI_INSTANCE_DIR . '/custom/commands/*.php',
        'tools' => YESWIKI_SOURCE_DIR . '/tools/*/commands/*.php',
    ] as $type => $search) {
    $files = glob($search);
    foreach ($files as $filePath) {
        $filename = pathinfo($filePath)['filename'];
        switch ($type) {
            case 'core':
                $className = "\\YesWiki\\Core\\Commands\\$filename";
                break;
            case 'custom':
                $className = "\\YesWiki\\Custom\\Commands\\$filename";
                break;
            case 'tools':
                $toolName = ucfirst(strtolower(basename(dirname(dirname($filePath)))));
                $className = "\\YesWiki\\$toolName\\Commands\\$filename";
                break;
            default:
                $className = "";
                break;
        }
        $command = new $className($wiki);
        if ($command) {
            $application->add($command);
        }
    }
}

$application->run();
