parameters:
  use_alerte: true # alerte pour quitter le mode édition
  altcha: true
  wiki_status: 'running' # status of the wiki ('running','maintenance','hibernation')
  security_editable_config_params:
    - 'use_alerte'
    - 'altcha'
    - 'wiki_status'
    - archive:
        - privatePath
        - call_archive_async
        - max_nb_files
        - preupdate_backup_activated

services:
  _defaults:
    autowire: true
    public: true

  # Allows to use controllers as services
  YesWiki\Security\Controller\:
    resource: 'controllers/*'
