parameters:
  admin_pages_to_update:
    - BazaR
    - GererSite
    - GererDroits
    - GererDroitsActions
    - GererDroitsHandlers
    - GererMisesAJour
    - GererThemes
    - GererConfig
    - GererUtilisateurs
    - TableauDeBord
    - LookWiki
    - GererSauvegardes

services:
  _defaults:
    autowire: true
    public: true

  YesWiki\AutoUpdate\Service\:
    resource: 'services/*'
