name: Docker Image

on:
  push:
    paths-ignore:
    - '**/*.md'
    - 'files/**/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build -t yeswiki/yeswiki .

    # - uses: jerray/publish-docker-action@v1.0.5
    #   with:
    #     repository: yeswiki/yeswiki
    #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
    #     password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    #     auto_tag: true