name: Docker Image

on:
  push:
    paths:
      - docker/dockerfile
      - docker/docker-compose*.yml
      - .github/workflows/docker.yml

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Build a Docker image able to run yeswiki
        run: docker build -f docker/dockerfile-prod -t yeswiki/yeswiki .
